Repository dragonflyoss/Dragonfly, pull requests merged in 2018-11, with the labels that each got.

#189 docs: add shellcheck to validate shell scripts
  .circleci/config.yml
  build/build.sh
  build/client/env.sh
  build/client/run.sh
  build/supernode/supernode-build.sh
Labels: areas/docs, size/L

#199 chore: fix go vet check failure and misspell of shell scripts
  build/client/run.sh
  build/supernode/supernode-build.sh
Labels: LGTM, kind/bug, size/S

#196 docs: reduce MD002 MD007 MD026 rule for markdownlint
  .circleci/config.yml
Labels: areas/docs, size/XS

#201 refactor: some changes about the code of dfdaemon
  cmd/dfdaemon/main.go
  cmd/dfdaemon/options/options.go
  cmd/dfdaemon/options/options_test.go
  dfdaemon/handler/dfgetter.go
  dfdaemon/handler/root_handler.go
  dfdaemon/handler/transport.go
Labels: LGTM, kind/refactor, size/L

#192 docs: revamped chapter 0-3 and removed unwanted level-1 headings
  docs/.build/config.toml
  docs/_index.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/images/bt_mini_toc_en.png
  docs/images/f_search_box_en.png
  docs/images/sc_mini_toc_en.png
  docs/maintainers.md
  docs/onboarding/_index.md
  docs/overview/terminology.md
  docs/overview/what_is_dragonfly.md
  docs/quick_start/_index.md
  docs/roadmap.md
  docs/user_guide/_index.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/supernode_configuration.md
Labels: LGTM, areas/docs, size/XXL

#204 docs: define preheat api using swagger
  apis/swagger.yml
  apis/types/error.go
  apis/types/error_response.go
  apis/types/peer_create_request.go
  apis/types/peer_create_response.go
  apis/types/peer_info.go
  apis/types/piece_info.go
  apis/types/piece_update_request.go
  apis/types/preheat_create_request.go
  apis/types/preheat_create_response.go
  apis/types/preheat_info.go
  apis/types/task_create_request.go
  apis/types/task_create_response.go
  apis/types/task_info.go
  apis/types/task_update_request.go
Labels: areas/docs, size/XL

#198 lint: make gocode validated by gometalinter
  .circleci/config.yml
  dfdaemon/util/netutil.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/util/file_util_test.go
Labels: size/M

#209 docs: add preheat list API endpoint in swagger.yml
  apis/swagger.yml
Labels: areas/docs, size/S

#213 chore: create links to clients in /usr/local/bin
  build/build.sh
  build/client/env.sh
  build/client/run.sh
Labels: size/M

#210 feature: add preheat client sdk for supernode
  client/client.go
  client/httputils.go
  client/interface.go
  client/preheat_create.go
  client/preheat_info.go
  client/preheat_list.go
  client/request.go
  client/utils.go
Labels: kind/feature, size/XL

#224 docs: remove commercial support part in README.md
  README.md
  docs/_index.md
Labels: areas/docs, size/XS

#222 feature: rewrite supernode server with golang
  supernode/config/config.go
  supernode/daemon/daemon.go
  supernode/main.go
  supernode/server/handler.go
  supernode/server/router.go
  supernode/server/server.go
  supernode/server/system_bridge.go
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/context_gorilla.go
  vendor/github.com/gorilla/mux/context_native.go
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#231 docs: revised chapter 4-6; removed hugo shortcodes; changed base URL …
  apis/README.md
  docs/.build/config.toml
  docs/_index.md
  docs/api_reference/_index.md
  docs/api_reference/api_preheat.md
  docs/api_reference/api_supernode.md
  docs/cli_reference/dfdaemon.md
  docs/cli_reference/dfget.md
  docs/faq/_index.md
  docs/overview/terminology.md
  docs/overview/what_is_dragonfly.md
  docs/quick_start/_index.md
  docs/roadmap.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/supernode_configuration.md
Labels: areas/docs, size/XXL

#238 docs: use custom git-pages domain
  wercker.yml
Labels: areas/docs, size/XS

#236 docs: fix some typos and dead git addr
  README.md
  apis/README.md
  docs/faq/_index.md
  docs/onboarding/_index.md
  docs/quick_start/_index.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
Labels: areas/docs, areas/typo, size/M

#229 linter: add markdown-link-check for dead link in doc
  .circleci/config.yml
  CONTRIBUTING.md
  apis/README.md
  docs/overview/what_is_dragonfly.md
  docs/zh/install_client.md
Labels: LGTM, size/S

#243 docs: update company name for zhouhaibing089
  MAINTAINERS.md
Labels: LGTM, areas/docs, size/XS

#245 fix: dead image link in hugo pages
  docs/.build/prepare.sh
Labels: kind/bug, size/XS

#208 feature: add Dockerfile of dfclient
  Dockerfile
Labels: kind/feature, size/S
