Repository dragonflyoss/Dragonfly, pull requests merged in 2018-12, with the labels that each got.

#253 fix: bad link of dfget example
  docs/quick_start/_index.md
Labels: kind/bug, size/XS

#254 fix: don't replace '../images' in code block
  docs/.build/prepare.sh
Labels: kind/bug, size/XS

#262 fix: remove unused code and polish log
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/BaseWorker.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/FilePreheater.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/ImagePreheater.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/PreheatServiceImpl.java
Labels: areas/log, kind/bug, size/S

#265 feature: implement powerClient and finishTask to implement the basic functions of dfget
  .gitignore
  dfget/cli/cli.go
  dfget/core/downloader/p2p_downloader.go
  dfget/core/downloader/power_client.go
Labels: kind/feature, size/XL

#257 refactor: use cobra to implement the dfget client
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/dfget/app/version.go
  cmd/dfget/main.go
  dfget/cli/cli.go
  dfget/cli/cli_parameters.go
  dfget/cli/cli_test.go
  dfget/core/downloader/downloader.go
  dfget/core/regist/register.go
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/suite.go
  vendor/vendor.json
Labels: LGTM, kind/refactor, size/XL, size/XXL

#270 docs: fix bad link caused by the change of d7y.io
  FAQ.md
  README.md
  apis/README.md
  docs/README.md
  docs/api_reference/README.md
  docs/apis.md
  docs/cli_reference/README.md
  docs/faq/README.md
  docs/quick_start/README.md
  docs/user_guide/README.md
  docs/user_guide/download_files.md
Labels: LGTM, areas/docs, size/S

#269 doc: add an image of sequence diagram
  docs/images/api_sequence_diagram.png
Labels: areas/docs, size/XS

#273 chore: update nginx.conf to serve all apis of supernode
  src/supernode/src/main/docker/sources/nginx.conf
Labels: size/XS

#274 chore: remove wercker
  docs/.build/archetypes/default.md
  docs/.build/config.toml
  docs/.build/i18n/en.toml
  docs/.build/i18n/zh-cn.toml
  docs/.build/layouts/partials/logo.html
  docs/.build/prepare.sh
  docs/.build/static/css/theme-dragonfly.css
  docs/.build/themes/.keep
  wercker.yml
Labels: LGTM, size/XL

#261 Rewrite dockerfile to make the image smaller
  Dockerfile
  dfdaemon/initializer/initializer.go
Labels: LGTM, size/S

#266 feature: polish API definition in swagger
  apis/swagger.yml
  apis/types/error.go
  apis/types/error_response.go
  apis/types/peer_create_request.go
  apis/types/peer_create_response.go
  apis/types/peer_info.go
  apis/types/piece_info.go
  apis/types/piece_update_request.go
  apis/types/preheat_create_request.go
  apis/types/preheat_create_response.go
  apis/types/preheat_info.go
  apis/types/task_create_request.go
  apis/types/task_create_response.go
  apis/types/task_info.go
  apis/types/task_update_request.go
Labels: kind/feature, size/XL

#276 refactor: unify the developing and test environment
  .circleci/config.yml
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  build/build.sh
  build/client/Makefile
  build/client/configure
  build/client/env.sh
  build/client/run.sh
  build/supernode/supernode-build.sh
  hack/build-supernode-image.sh
  hack/check-client.sh
  hack/check-supernode.sh
  hack/compile-supernode.sh
  hack/env.sh
  hack/install-client.sh
  hack/unit-test.sh
Labels: areas/test, kind/refactor, size/XXL

#279 docs: update installing documents and quick-start
  docs/quick_start/README.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
Labels: areas/docs, size/L

#280 fix: remove redundant log and output correct file length
  cmd/dfget/app/root.go
  dfget/config/config.go
  dfget/core/core.go
  dfget/core/downloader/p2p_downloader.go
Labels: areas/log, kind/bug, size/S

#278 feature: update API definition to be more accurate
  apis/swagger.yml
  apis/types/peer_create_request.go
  apis/types/peer_create_response.go
  apis/types/peer_info.go
  apis/types/piece_info.go
  apis/types/piece_update_request.go
  apis/types/task_create_request.go
  apis/types/task_create_response.go
  apis/types/task_info.go
  apis/types/task_update_request.go
Labels: kind/feature, size/XL

#282 feature: implement dfget uploader server
  cmd/dfget/app/root.go
  dfget/core/downloader/p2p_downloader.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_util.go
  dfget/core/uploader/uploader_util_test.go
  dfget/util/http_util.go
Labels: kind/feature, size/XL
