Repository dragonflyoss/Dragonfly, pull requests merged in 2018-10, with the labels that each got.

#155 docs: complete the roadmap.md
  ROADMAP.md
Labels: documentation

#158 docs: [test] revising doc Installing Client
  docs/zh/install_client.md
Labels: documentation

#162 rafactor: remove the code that will never happen
  dfdaemon/util/netutil.go
Labels: LGTM, kind/refactor

#165 docs: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: LGTM, areas/docs

#163 docs: update readme to add more info
  AUTHORS
  CHANGELOG.md
  CONTRIBUTING.md
  CONTRIBUTORS
  README.md
  hack/generate-contributors.sh
Labels: LGTM, areas/docs

#168 comments: add comments of fields of struct
  cmd/dfdaemon/options/options.go
  dfdaemon/global/global.go
  dfget/cli/cli_parameters.go
  dfget/config/config.go
Labels: size/XL

#174 feature: add blocking queue
  dfget/util/queue.go
  dfget/util/queue_test.go
Labels: kind/feature, size/XL

#176 comments: make struct filed Notbs comments consistent accross multipl…
  cmd/dfdaemon/options/options.go
  dfget/config/config.go
Labels: size/XS

#178 comments: fix some typos in queue.go
  dfget/util/queue.go
Labels: areas/typo, size/S

#180 docs: add hugo documents framework
  .gitignore
  docs/.build/archetypes/default.md
  docs/.build/config.toml
  docs/.build/layouts/partials/logo.html
  docs/.build/static/css/theme-dragonfly.css
  docs/.build/themes/.keep
  wercker.yml
Labels: areas/docs, size/L

#181 docs: adjust documents structure
  docs/.build/config.toml
  docs/.build/i18n/en.toml
  docs/.build/i18n/zh-cn.toml
  docs/_config.yml
  docs/_index.md
  docs/api_reference/_index.md
  docs/api_reference/api_preheat.md
  docs/api_reference/api_supernode.md
  docs/cli_reference/_index.md
  docs/cli_reference/dfdaemon.md
  docs/cli_reference/dfget.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/documents.md
  docs/en/LICENSE
  docs/en/README.md
  docs/en/adoptors.md
  docs/en/architecture.md
  docs/en/what_is_dragonfly.md
  docs/faq/_index.md
  docs/maintainers.md
  docs/onboarding/_index.md
  docs/overview/_index.md
  docs/overview/terminology.md
  docs/overview/what_is_dragonfly.md
  docs/quick_start/_index.md
  docs/roadmap.md
  docs/template/ISSUE_TEMPLATE.md
  docs/template/PULL_REQUEST_TEMPLATE.md
  docs/user_guide/_index.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/supernode_configuration.md
  wercker.yml
Labels: areas/docs, size/XXL

#182 docs: fix invalid links in markdown
  CONTRIBUTING.md
  FAQ.md
  README.md
Labels: areas/docs, size/S

#164 refactor: make CI parallel and add code and doc checking
  .circleci/config.yml
  CONTRIBUTING.md
  FAQ.md
  README.md
  docs/_index.md
  docs/api_reference/api_preheat.md
  docs/api_reference/api_supernode.md
  docs/cli_reference/dfdaemon.md
  docs/cli_reference/dfget.md
  docs/code_of_conduct.md
  docs/contributing.md
  docs/faq/_index.md
  docs/onboarding/_index.md
  docs/overview/terminology.md
  docs/overview/what_is_dragonfly.md
  docs/quick_start/_index.md
  docs/roadmap.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/supernode_configuration.md
  docs/zh/README.md
  docs/zh/install_client.md
  docs/zh/install_server.md
  docs/zh/usage.md
  src/README.md
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/util/RangeParseUtil.java
Labels: areas/test, kind/refactor, size/XL

#186 docs: Update issue templates
  .github/ISSUE_TEMPLATE/any-questions-on-dragonfly.md
  .github/ISSUE_TEMPLATE/bug-report-for-dragonfly.md
  .github/ISSUE_TEMPLATE/feature-request-of-dragonfly.md
Labels: areas/docs, size/M

#185 docs: add dragonfly logos in repo and remove useless issue template
  .github/ISSUE_TEMPLATE.md
  README.md
  docs/images/logo/dragonfly-linear.png
  docs/images/logo/dragonfly-linear.svg
  docs/images/logo/dragonfly-vertical.png
  docs/images/logo/dragonfly.svg
Labels: areas/docs, areas/log, size/S

#188 docs: add install dfclient commands to QuickStart
  docs/quick_start/_index.md
Labels: LGTM, areas/cli, areas/docs, size/S

#179 fix http cache miss for servers which supports etag only
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/domain/FileMetaData.java
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/util/HttpClientUtil.java
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/CacheDetectorImpl.java
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/Downloader.java
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/FileMetaDataService.java
  src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/impl/FileMetaDataServiceImpl.java
Labels: kind/bug, size/S
