Repository dragonflyoss/Dragonfly, pull requests merged in 2019-01, with the labels that each got.

#298 fix: make invalid link in apis.md pass markdown-link-check
  apis/swagger.yml
  apis/types/task_create_request.go
  docs/apis.md
Labels: kind/bug, size/S

#290 fix markdown format for this document
  docs/zh/install_server.md
Labels: LGTM, areas/docs, size/XS

#302 docs: add more questions in FAQ.md
  FAQ.md
Labels: LGTM, areas/docs, kind/question, size/L

#303 docs: remove wangj998 and add Starnop in MAINTAINER.md
  MAINTAINERS.md
Labels: LGTM, areas/docs, size/XS

#308 ci: add gocyclo support in circle CI test
  .circleci/config.yml
Labels: areas/test, size/XS

#309 doc: add roadmap doc for better community building
  ROADMAP.md
  docs/roadmap.md
Labels: areas/docs, size/L

#305 refactor: refactor dfdaemon cmd part with by spf13/cobra
  cmd/dfdaemon/app/options/options.go
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/main.go
  cmd/dfdaemon/options/options_test.go
  cmd/dfget/app/root_test.go
  dfdaemon/initializer/initializer.go
Labels: LGTM, kind/refactor, size/XL

#286 refactor: update context to config in dfget
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/core/downloader/back_downloader.go
  dfget/core/downloader/back_downloader_test.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/p2p_downloader.go
  dfget/core/downloader/power_client.go
  dfget/core/helper/test_helper.go
  dfget/core/regist/register.go
  dfget/core/regist/register_test.go
  dfget/core/uploader/uploader.go
Labels: LGTM, kind/refactor, size/XXL

#314 docs: add README in vendor dir to illustrate the vendor policy
  CONTRIBUTING.md
Labels: areas/docs, size/S

#319 doc: add some FAQs about sequence
  FAQ.md
  docs/cli_reference/dfget.md
Labels: LGTM, areas/docs, size/M

#321 bugfix: update rootCmd of dfget from PersistentFlags to Flags
  cmd/dfget/app/root.go
Labels: kind/bug, size/S

#312 feature: add gen-doc command to auto gen dfget cli docs
  cmd/dfget/app/gen_doc.go
  cmd/dfget/app/root.go
  docs/cli_reference/dfget.md
  docs/cli_reference/dfget_gen-doc.md
  docs/cli_reference/dfget_version.md
  vendor/github.com/cpuguy83/go-md2man/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/md2man/roff.go
  vendor/github.com/russross/blackfriday/LICENSE.txt
  vendor/github.com/russross/blackfriday/README.md
  vendor/github.com/russross/blackfriday/block.go
  vendor/github.com/russross/blackfriday/doc.go
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/inline.go
  vendor/github.com/russross/blackfriday/latex.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/smartypants.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/vendor.json
Labels: areas/cli, kind/feature, size/XXL

#316 feature: add the build option of the client in the local environment
  .gitignore
  Makefile
  hack/build-client-local.sh
Labels: kind/feature, size/M

#310 docs: support private image which needs user/passwd for remote registries
  docs/user_guide/download_files.md
  docs/zh/usage.md
Labels: areas/docs, size/S

#326 refactor: client launches an independent peer server when downloading files in p2p pattern
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  dfget/config/config.go
  dfget/config/constants.go
  dfget/config/metadata.go
  dfget/config/metadata_test.go
  dfget/core/core.go
  dfget/core/downloader/p2p_downloader.go
  dfget/core/helper/file_helper.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_util.go
  dfget/core/uploader/uploader_util_test.go
  dfget/util/http_util.go
Labels: size/XXL

#331 docs: update FAQ to add private image supporting way
  FAQ.md
Labels: areas/docs

#300 doc: The first draft of the design document
  docs/design/design.md
  docs/design/dfget_supernode.puml
  docs/images/design/architecture.png
  docs/images/design/dfget_supernode.png
  docs/images/design/download.png
  docs/images/design/register.png
  docs/images/design/service_down.png
Labels: areas/docs, size/XL

#333 docs: reorganize documents structure of Dragonfly
  apis/README.md
  docs/README.md
  docs/api_reference/README.md
  docs/api_reference/apis.md
  docs/cli_reference/README.md
  docs/ecosystem/Harbor-with-Dragonfly.md
  docs/ecosystem/Kubernetes-with-Dragonfly.md
  docs/faq/README.md
  docs/onboarding/_index.md
  docs/overview/_index.md
  docs/overview/terminology.md
  docs/overview/what_is_dragonfly.md
  docs/quick_start/README.md
  docs/test_guide/test_guide.md
  docs/zh/README.md
  docs/zh/api.md
  docs/zh/architecture.md
  docs/zh/install_client.md
  docs/zh/install_server.md
  docs/zh/usage.md
Labels: areas/docs

#284 feature: Define supernode components and interfaces
  apis/swagger.yml
  apis/types/df_get_task.go
  apis/types/piece_update_request.go
  apis/types/task_create_request.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler_mgr.go
  supernode/daemon/mgr/task_mgr.go
Labels: kind/feature, size/XL

#357 style: make log's output more clear and readable
  dfget/core/downloader/p2p_downloader.go
  dfget/core/downloader/power_client.go
  dfget/types/pull_piece_task_response.go
  dfget/types/types_test.go
  dfget/util/log.go
  dfget/util/log_test.go
  src/supernode/src/main/resources/logback.xml
Labels: size/L

#360 refactor: untify the api of uploader
  dfget/config/constants.go
  dfget/core/api/download_api.go
  dfget/core/api/uploader_api.go
  dfget/core/api/uploader_api_types.go
  dfget/core/downloader/back_downloader.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/p2p_downloader.go
  dfget/core/downloader/power_client.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_util.go
  dfget/util/http_util.go
Labels: areas/df-get, kind/refactor, size/XL

#358 fix: optimize the judgment of local cache expiration
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/HttpClientUtil.java
Labels: kind/bug, size/XS, supernode-Java
