Repository dragonflyoss/Dragonfly, pull requests merged in 2019-08, with the labels that each got.

#762 fix initiliazed => initialized
  dfget/core/uploader/peer_server_executor.go
Labels: size/XS

#764 optimize error description
  dfget/core/uploader/peer_server_executor.go
Labels: LGTM, kind/bug, size/XS

#752 bugfix: the dfget will always receive fail result when change supernode
  supernode/server/0.3_bridge.go
Labels: kind/bug, size/XS

#769 docs: add daocloud adopter
  adopters.md
  docs/images/adoptor_logo/DaoCloud.png
Labels: LGTM, areas/docs, size/XS

#772 fix word `managered` to `managed`
  docs/design/design.md
Labels: size/XS

#770 fix a to an in annotation
  client/client.go
  common/errors/supernode_errors.go
  supernode/daemon/mgr/scheduler/manager.go
  test/main_test.go
Labels: size/XS

#727 feature: add access time for taskID
  .gitignore
  common/util/sys_util.go
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task_mgr.go
Labels: kind/feature, size/M

#777 fix some typos in comment
  common/util/net_util.go
  common/util/sync_map_util.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/regist/register.go
  supernode/config/config.go
Labels: areas/typo, size/S

#739 bugfix: return error when the url is unreachable
  dfget/core/regist/register.go
  pkg/timeutils/time_util.go
  supernode/config/config.go
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task/manager_util_test.go
  supernode/server/result_info.go
Labels: kind/bug, size/L

#774 move some log level to debug
  cmd/dfdaemon/app/init.go
  supernode/server/0.3_bridge.go
Labels: areas/log, chore, size/XS

#771 feature: add golbal dfget params to the dfdaemon config
  cmd/dfdaemon/app/root.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/downloader/dfget/dfget.go
Labels: kind/feature, size/M

#786 bugfix: fix bug unknown profile
  supernode/server/router.go
  supernode/server/router_test.go
Labels: kind/bug, size/S

#787 cleanup: log message typo fix
  dfget/core/uploader/peer_server.go
Labels: areas/log, areas/typo, size/XS

#763 docs: improve docs
  FAQ.md
  docs/user_guide/download_files.md
Labels: areas/docs, size/XS

#798 docs/readme.md: cleanup typo in dcos
  docs/README.md
Labels: LGTM, areas/typo, size/XS

#797 storage_driver.go: property name be "offset"
  supernode/store/storage_driver.go
Labels: LGTM, areas/typo, size/XS

#735 feature: supernode support download remote file by setting tls config.
  apis/swagger.yml
  apis/types/task_register_request.go
  cmd/dfget/app/root.go
  dfdaemon/config/config.go
  dfdaemon/downloader/dfget/dfget.go
  dfget/config/config.go
  dfget/core/regist/register.go
  dfget/types/register_request.go
  pkg/httputils/http_util.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/downloader_test.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_test.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task/manager_util_test.go
  supernode/httpclient/mock/mock_origin_http_client.go
  supernode/httpclient/origin_http_client.go
  supernode/server/0.3_bridge.go
  supernode/server/server.go
Labels: kind/feature, size/XXL

#805 http_util.go: fix word in error message
  pkg/httputils/http_util.go
Labels: LGTM, kind/bug, size/XS

#808 fix mis-spelling in multi_machines_deployment.md
  docs/user_guide/multi_machines_deployment.md
Labels: LGTM, size/XS

#804 docs: add EddieHuang as a maintainer
  MAINTAINERS.md
Labels: LGTM, areas/docs, size/XS

#812 fix wrong spells in config.go
  dfget/config/config.go
Labels: LGTM, size/XS

#811 cleanup: server.go flag help massage typo fix
  cmd/dfget/app/server.go
Labels: areas/typo, size/XS

#795 feature: not return error directly when failed to get http file Length
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, kind/feature, size/XS

#807 feature: add boilerplate check script
  cmd/dfdaemon/app/init.go
  cmd/dfdaemon/app/root_test.go
  cmd/dfdaemon/app/version.go
  cmd/supernode/app/version.go
  dfdaemon/proxy/proxy.go
  dfdaemon/proxy/proxy_test.go
  dfdaemon/server.go
  hack/boilerplate/check-boilerplate.go
  hack/boilerplate/check-boilerplate_test.go
  hack/check.sh
  pkg/ratelimiter/ratelimiter.go
  pkg/util/metrics_util.go
  supernode/config/config.go
  supernode/daemon/daemon.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/reporter.go
  supernode/daemon/mgr/cdn/super_reader.go
  supernode/daemon/mgr/cdn/super_writer.go
  supernode/daemon/mgr/cdn/super_writer_util.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/progress/piece_state.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_state.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress/state_sync_map.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/scheduler_mgr.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task_mgr.go
  supernode/daemon/util/filter.go
  supernode/daemon/util/store.go
  supernode/httpclient/origin_http_client.go
  supernode/server/0.3_bridge.go
  supernode/server/handler.go
  supernode/server/metrics.go
  supernode/server/peer_bridge.go
  supernode/server/result_info.go
  supernode/server/router.go
  supernode/server/router_test.go
  supernode/server/server.go
  supernode/server/system_bridge.go
  test/api_metrics_test.go
  test/api_ping_test.go
  test/environment/env.go
  test/main_test.go
  test/request/request.go
  test/util_api.go
Labels: LGTM, kind/feature, size/XXL

#816 Update indentation of comments
  test/README.md
Labels: LGTM, size/XS

#742 bugfix: the dfget will wait forever when the final piece failed
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/bug, size/XS

#759 feature: add some supernode metrics
  dfdaemon/constant/constant.go
  dfdaemon/server.go
  docs/user_guide/metrics.md
  docs/user_guide/monitoring.md
  go.mod
  go.sum
  pkg/metricsutils/metrics_util.go
  pkg/timeutils/time_util.go
  pkg/util/metrics_util.go
  supernode/daemon/daemon.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/dfgettask/manager_test.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/peer/manager_test.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_test.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task/manager_util_test.go
  supernode/server/metrics.go
  supernode/server/router.go
  supernode/server/router_test.go
  supernode/server/server.go
  test/api_metrics_test.go
  version/version.go
Labels: kind/feature, size/XXL

#821 cleanup: fix typos in root.go and dfget.md
  cmd/dfget/app/root.go
  docs/cli_reference/dfget.md
Labels: areas/typo, size/XS

#820 bugfix: update dfgettask status to success
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, size/XS

#822 fix mis-spelling in README.md
  test/README.md
Labels: size/XS

#825 Use constant blocks to define constants instead of discrete definitions.
  client/httputils.go
Labels: LGTM, size/S

#785 docs: update docs for release 0.4.3
  docs/quick_start/README.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/monitoring.md
  docs/user_guide/multi_machines_deployment.md
Labels: areas/docs, size/S

#828 fix some typos in README.md
  README.md
Labels: areas/typo, size/XS

#831 feature: update the roadmap for a new stage
  ROADMAP.md
Labels: LGTM, size/L

#779 feature: add gc mgr for supernode
  cmd/supernode/app/root.go
  dfget/core/downloader/p2p_downloader/power_client.go
  pkg/syncmap/syncmap.go
  supernode/config/config.go
  supernode/config/constants.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/piece_md5_mgr.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/gc/gc_dfget_task.go
  supernode/daemon/mgr/gc/gc_manager.go
  supernode/daemon/mgr/gc/gc_peer.go
  supernode/daemon/mgr/gc/gc_task.go
  supernode/daemon/mgr/gc_mgr.go
  supernode/daemon/mgr/mock/mock_cdn_mgr.go
  supernode/daemon/mgr/mock/mock_dfget_task_mgr.go
  supernode/daemon/mgr/mock/mock_peer_mgr.go
  supernode/daemon/mgr/mock/mock_progress_mgr.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/progress/progress_delete.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/state_sync_map.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task_mgr.go
  supernode/daemon/util/store.go
  supernode/server/0.3_bridge.go
  supernode/server/server.go
  supernode/util/locker.go
Labels: kind/feature, size/XXL

#837 docs: update the roadmap doc
  ROADMAP.md
Labels: LGTM, areas/docs, size/XS

#834 apis/swagger.yml: cleanup by fix some typos
  apis/swagger.yml
  apis/types/df_get_task.go
Labels: LGTM, areas/typo, size/S

#814 feature: replace gometalinter with golangci-lint
  .circleci/config.yml
  .golangci.yml
  Makefile
  dfget/core/api/supernode_api.go
  dfget/core/api/supernode_api_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  hack/build.sh
  hack/golangci-lint.sh
Labels: chore, kind/feature, size/L

#841 cleanup some unused dfget config fields
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/config/config_test.go
Labels: chore, size/S

#813 Feature: add code boilerplate check into circleci
  .circleci/config.yml
  Makefile
  hack/boilerplate-check.sh
  hack/boilerplate/check-boilerplate.go
  hack/check.sh
  supernode/daemon/mgr/gc/gc_dfget_task.go
  supernode/daemon/mgr/gc/gc_manager.go
  supernode/daemon/mgr/gc/gc_peer.go
  supernode/daemon/mgr/gc/gc_task.go
  supernode/daemon/mgr/gc_mgr.go
  supernode/daemon/mgr/progress/progress_delete.go
Labels: LGTM, areas/test, kind/feature, size/L

#849 bugfix: dfdaemon's config supernodes as an alias do not work.
  cmd/dfdaemon/app/root.go
Labels: kind/bug, size/XS

#854 bugfix: prevent dfgettask metrics < 0
  supernode/daemon/mgr/dfgettask/manager.go
Labels: kind/bug, size/XS

#852 bugfix:modify dfget output
  cmd/dfdaemon/app/version.go
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/dfget/app/server.go
  cmd/dfget/app/version.go
  cmd/supernode/app/version.go
  dfget/core/core.go
  dfget/core/downloader/back_downloader/back_downloader.go
Labels: kind/bug, size/S

#860 chore: remove trailing spaces in dfget example
  cmd/dfget/app/root.go
Labels: LGTM, size/XS

#862 fix-typo
  dfget/config/metadata.go
  docs/design/design.md
  supernode/daemon/mgr/cdn/file_meta_data.go
Labels: LGTM, areas/typo, size/XS

#783 refactor: new api for dflog and output log to console by default
  cmd/dfdaemon/app/init.go
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
  go.mod
  go.sum
  pkg/dflog/log.go
  pkg/dflog/log_test.go
Labels: areas/log, kind/refactor, size/XL

#809 feature: enable staticcheck
  .golangci.yml
  client/request.go
  dfget/core/api/supernode_api_test.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader.go
  supernode/daemon/mgr/dfgettask/manager_test.go
Labels: LGTM, kind/feature, size/S

#823 refactor: update some code and output logs for supernode
  supernode/daemon/mgr/scheduler/manager.go
Labels: areas/log, kind/refactor, size/S

#872 delete extra slash
  pkg/httputils/mock_http_util.go
Labels: size/XS
