Repository dragonflyoss/Dragonfly, pull requests merged in 2019-10, with the labels that each got.

#964 fix(dfdaemon): add error handling
  dfdaemon/handler/env_handler.go
  dfdaemon/handler/param_handler.go
  dfdaemon/proxy/proxy.go
  dfdaemon/server.go
Labels: kind/bug, size/S

#975 dfget&&supernode: cleanup code based on staticcheck warnings
  dfget/core/api/supernode_api_test.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/uploader/peer_server.go
  supernode/daemon/mgr/pieceerror/manager.go
Labels: LGTM, size/S

#994 bugfix: remove duplicate rate.MB
  supernode/config/config.go
Labels: kind/bug, size/XS

#981 feature: enable viper for supernode
  cmd/supernode/app/options.go
  cmd/supernode/app/root.go
  cmd/supernode/app/root_test.go
  supernode/config/config.go
Labels: kind/feature, size/XL

#1005 feature: upgrade golang version to 1.12.10
  .circleci/config.yml
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.supernode
  cmd/dfdaemon/app/version.go
  cmd/dfget/app/version.go
  cmd/supernode/app/version.go
  docs/cli_reference/dfdaemon_version.md
  docs/cli_reference/dfget_version.md
  hack/build.sh
  test/README.md
Labels: LGTM, kind/feature, size/S

#1003 version: add error handling
  version/version.go
Labels: LGTM, kind/bug, size/XS

#1009 update pouchlinter to 0.2.4
  .circleci/config.yml
  .travis.yml
Labels: size/XS

#953 feature: add a warn log for long gc duration
  dfget/core/downloader/p2p_downloader/power_client.go
  supernode/daemon/mgr/gc/gc_peer.go
  supernode/daemon/mgr/gc/gc_task.go
Labels: LGTM, areas/log, kind/feature, size/S

#990 bugfix:fix debug mod and homedir config in yaml
  cmd/supernode/app/root.go
Labels: kind/bug, size/S

#943 Using GOPROXY environment variables if set instead of default value
  Makefile
  hack/env.sh
Labels: size/S

#988 doc: add a doc about how to configure supernode,dfget,dfdaemon
  docs/config/README.md
  docs/config/dfdaemon_config_template.yml
  docs/config/dfdaemon_properties.md
  docs/config/dfget_config_template.yml
  docs/config/dfget_properties.md
  docs/config/supernode_config_template.yml
  docs/config/supernode_properties.md
Labels: areas/docs, kind/question, size/XL

#973 bugfix: set tls config if existed when dfget downloads from the sourc…
  dfget/core/downloader/back_downloader/back_downloader.go
  pkg/httputils/http_util.go
Labels: kind/bug, size/M

#1017 bugfix: delete the default value for supernodes from dfdaemon
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/app/root_test.go
  dfdaemon/downloader/dfget/dfget.go
Labels: kind/bug, size/XS

#1020 feature: add piece error handler API for supernode
  supernode/daemon/mgr/gc/gc_task.go
  supernode/server/0.3_bridge.go
  supernode/server/router.go
Labels: kind/bug, kind/feature, size/M

#1032 bug fix dfget client timeout set error when fileLength is 0
  dfget/core/core.go
Labels: LGTM, kind/bug, size/XS

#1019 feature: support set home dir in dfget config file.
  cmd/dfdaemon/app/init.go
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/root.go
  dfdaemon/config/config.go
  dfget/config/config.go
  dfget/core/uploader/peer_server_executor.go
Labels: size/L

#1039 docs: add Yum China as a Dragonfly adopter
  adopters.md
  docs/images/adoptor_logo/yum-china.png
Labels: areas/docs, size/XS
