Repository dragonflyoss/Dragonfly, pull requests merged in 2019-02, with the labels that each got.

#368 fix: update copyright to Dragonfly Authors
  cmd/dfdaemon/app/gen_doc.go
  cmd/dfdaemon/app/options/options.go
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/main.go
  cmd/dfget/app/gen_doc.go
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/dfget/app/version.go
  dfdaemon/constant/code.go
  dfdaemon/downloader/dfget/dfget.go
  dfdaemon/downloader/downloader.go
  dfdaemon/exception/errors.go
  dfdaemon/global/global.go
  dfdaemon/handler/debug_handler.go
  dfdaemon/handler/env_handler.go
  dfdaemon/handler/param_handler.go
  dfdaemon/handler/root_handler.go
  dfdaemon/handler/transport.go
  dfdaemon/initializer/atime_darwin_amd64.go
  dfdaemon/initializer/atime_linux_amd64.go
  dfdaemon/initializer/initializer.go
  dfdaemon/muxconf/muxconf.go
  dfdaemon/util/netutil.go
  dfdaemon/util/urlutil.go
Labels: LGTM, kind/bug, size/XL

#359 feature: report downloaded piece's status to supernode
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  dfget/config/constants.go
  dfget/core/api/download_api.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/target_writer.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_test.go
  dfget/core/uploader/uploader_util.go
  dfget/core/uploader/uploader_util_test.go
  dfget/errors/errors.go
  dfget/util/limit_reader.go
  dfget/util/log.go
  dfget/util/log_test.go
Labels: LGTM, areas/supernode-go, kind/feature, size/XXL

#369 bugfix: fix rotating log makes dfdaemon.log file huge size
  dfdaemon/initializer/initializer.go
Labels: areas/log, kind/bug, size/M

#365 test: add mock test for api client and preheat API mock test
  client/client_mock_test.go
  client/preheat_info_test.go
  hack/env.sh
  hack/unit-test.sh
Labels: areas/test, size/XL

#372 refactor: directly config logrus' default Logger rather than create a new one
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/dfget/app/server.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/target_writer.go
  dfget/core/helper/test_helper.go
  dfget/core/regist/register.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_util.go
  dfget/util/log.go
Labels: areas/log, kind/refactor, size/XL

#376 feature: make cli of dfget more readable
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  dfget/config/config.go
Labels: kind/feature, size/M

#387 fix: correct typo and remove basepath
  apis/swagger.yml
  docs/api_reference/apis.md
Labels: areas/typo, kind/bug, size/XS

#388 move supernode to cmd/
  .circleci/config.yml
  cmd/supernode/main.go
Labels: LGTM, size/XS

#373 feature: add ping impelmentation in sdk and add mock test
  client/ping.go
  client/ping_test.go
Labels: areas/test, kind/feature, size/L

#378 feature: report peer server down when it passively exits
  dfget/core/api/uploader_api.go
  dfget/core/helper/test_helper.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_test.go
  dfget/core/uploader/uploader_util.go
  dfget/core/uploader/uploader_util_test.go
  dfget/util/limit_reader.go
Labels: LGTM, kind/feature, size/XXL

#393 feature: add 'docs' target in Makefile to generate API/CLI docs easily
  Makefile
  hack/build-client.sh
  hack/generate-docs.sh
Labels: LGTM, kind/feature, size/M

#394 docs: add more questions in FAQ.md
  FAQ.md
Labels: areas/docs, kind/question, size/S

#396 docs: update dfget commandline description to rm trailing spaces
  cmd/dfget/app/root.go
Labels: areas/cli, areas/docs, size/S

#384 feature: add peers actions in client pkg of golang sdk
  client/peer_create.go
  client/peer_delete.go
  client/peer_info.go
  client/peer_list.go
Labels: kind/feature, size/L

#401 refactor: refactor and add unit-test for peer_server_executor.go
  dfget/core/core_test.go
  dfget/core/helper/test_helper.go
  dfget/core/uploader/peer_server_executor.go
  dfget/core/uploader/peer_server_executor_test.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_util_test.go
Labels: areas/test, kind/refactor, size/XL

#402 test: add unit-test for module uploader of dfget
  dfget/core/api/uploader_api.go
  dfget/core/api/uploader_api_types.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_test.go
  dfget/core/uploader/uploader_util.go
  dfget/core/uploader/uploader_util_test.go
  dfget/util/http_util_test.go
Labels: areas/test, size/XXL

#407 log: unify project logs
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/dfget/app/version.go
  dfdaemon/initializer/initializer.go
  dflog/log.go
  dflog/log_test.go
Labels: areas/log, size/L

#413 fix: bindwidth -> bandwidth
  cmd/supernode/main.go
  supernode/config/config.go
Labels: kind/bug, size/S

#412 test: fix data race caused by TestLaunchPeerServer
  dfget/core/uploader/uploader_test.go
Labels: areas/test, size/XS

#414 feature: make client queue size configurable
  cmd/dfget/app/root.go
  dfget/config/config.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/feature, size/S

#415 fix: the speed will be slower and slower when multiple dfgets are executed consecutively on the same machine
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
Labels: kind/bug, size/XS

#418 comments: add comments for struct fields
  dfget/config/config.go
  dfget/config/metadata.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/piece.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/target_writer.go
Labels: size/XL

#423 Fix typo in README.md
  apis/README.md
Labels: areas/typo, size/XS

#410 feature: dfdaemon supports proxing https registries
  cmd/dfdaemon/app/options/options.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/global/global.go
  dfdaemon/handler/root_handler.go
  dfdaemon/handler/transport.go
  dfdaemon/initializer/initializer.go
  dfdaemon/muxconf/muxconf.go
  dfget/config/config.go
  dfget/config/constants.go
Labels: kind/feature, size/XL

#425 test: add unit tests for p2p downloader
  dfget/core/api/download_api.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/client_writer_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/p2p_downloader_test.go
  dfget/core/downloader/p2p_downloader/piece_test.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/downloader/p2p_downloader/target_writer.go
Labels: areas/test, size/XL

#426 fix: dfdaemon exit when load properties failed
  dfdaemon/constant/code.go
  dfdaemon/downloader/dfget/dfget.go
  dfdaemon/initializer/initializer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/bug, size/S

#391 build: populate version with ldflags
  hack/build-client.sh
  version/version.go
Labels: size/S

#430 fix: don't exit when default config file is not exist
  cmd/dfdaemon/app/options/options.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/constant/constant.go
  dfdaemon/initializer/initializer.go
Labels: kind/bug, size/S
