Repository dragonflyoss/Dragonfly, pull requests merged in 2019-04, with the labels that each got.

#462 added docker run desc
  docs/quick_start/README.md
Labels: size/S

#458 feature: implement the dfgetTaskMgr
  apis/swagger.yml
  apis/types/df_get_task.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfget_task_mgr_test.go
Labels: kind/feature, size/XL

#465 fix: fix the default download path of supernode
  supernode/config/config.go
Labels: kind/bug, size/XS

#466 refactor: extract errors in common folder
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  common/errors/errors.go
  common/errors/errors_test.go
  common/errors/supernode_errors.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/regist/register.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
  dfget/errors/errors.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfget_task_mgr_test.go
  supernode/daemon/mgr/filter.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/peer_mgr_test.go
  supernode/daemon/mgr/store.go
  supernode/daemon/mgr/store_test.go
  supernode/result/result_info.go
  supernode/server/peer_bridge.go
Labels: kind/bug, kind/refactor, size/XL

#471 feature: make supernode configurable for dfget with dfdaemon
  cmd/dfdaemon/app/options/options.go
  dfdaemon/downloader/dfget/dfget.go
  dfdaemon/global/global.go
  dfdaemon/handler/transport.go
  dfdaemon/initializer/initializer.go
Labels: kind/feature, size/S

#474 feature: Add an empty implementation of the CDN manager
  supernode/daemon/mgr/cdn_mgr.go
Labels: kind/feature, size/S

#475 comments: update the comments of ConfigFiles of dfget
  dfget/config/config.go
Labels: size/XS

#476 refactor: refactor the http utils as a common code
  common/util/http_util.go
  common/util/http_util_test.go
  common/util/mock_http_util.go
  dfget/core/api/api_test.go
  dfget/core/api/download_api.go
  dfget/core/api/supernode_api.go
  dfget/core/api/supernode_api_test.go
  dfget/core/api/uploader_api.go
  dfget/core/core.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader.go
  test/command/cmd.go
Labels: kind/refactor, size/XL

#480 feature: add config to disable cdn feature
  cmd/dfget/app/root.go
  dfget/config/config.go
  dfget/config/constants.go
  docs/quick_start/README.md
  docs/user_guide/install_client.md
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/Constants.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
Labels: kind/feature, size/M

#461 feature: implement progress mgr
  common/errors/errors.go
  common/errors/supernode_errors.go
  common/util/atomic_count.go
  common/util/sync_map_util.go
  common/util/sync_map_util_test.go
  supernode/config/constants.go
  supernode/daemon/mgr/progress/piece_state.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_state.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress/progress_util_test.go
  supernode/daemon/mgr/progress/state_sync_map.go
  supernode/daemon/mgr/progress_mgr.go
  vendor/github.com/willf/bitset/LICENSE
  vendor/github.com/willf/bitset/Makefile
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/popcnt.go
  vendor/github.com/willf/bitset/popcnt_19.go
  vendor/github.com/willf/bitset/popcnt_amd64.go
  vendor/github.com/willf/bitset/popcnt_amd64.s
  vendor/github.com/willf/bitset/popcnt_generic.go
  vendor/github.com/willf/bitset/trailing_zeros_18.go
  vendor/github.com/willf/bitset/trailing_zeros_19.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#482 refactor: refactor the supernode daemon dir
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/dfgettask/manager_test.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/peer/manager_test.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/util/filter.go
  supernode/daemon/util/filter_test.go
  supernode/daemon/util/store.go
  supernode/daemon/util/store_test.go
  supernode/server/peer_bridge.go
  supernode/server/server.go
Labels: kind/refactor, size/XXL

#484 dfget/config/config.go: Fix typo in comment
  dfget/config/config.go
  dfget/core/downloader/p2p_downloader/client_writer.go
Labels: areas/typo, size/XS

#488 Minor grammar/typo fixes in README
  README.md
Labels: areas/typo, size/XS

#491 bugfix: unify the peer port type to int32
  apis/swagger.yml
  apis/types/piece_info.go
Labels: kind/bug, size/XS

#492 refactor: update the interface of task mgr
  apis/swagger.yml
  apis/types/piece_info.go
  apis/types/piece_pull_request.go
  apis/types/piece_update_request.go
  supernode/daemon/mgr/task_mgr.go
Labels: kind/refactor, size/XL

#483 feature: implement the progress mgr for get/delete info
  common/errors/errors.go
  common/errors/supernode_errors.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_manager_test.go
  supernode/daemon/mgr/progress/progress_state.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress/progress_util_test.go
  supernode/daemon/mgr/progress_mgr.go
Labels: kind/feature, size/XL

#495 feature: implement an empty scheduler and update the interface
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/scheduler_mgr.go
Labels: kind/feature, size/S

#497 bugfix: no need to return error if the result is nil when get pieces
  supernode/daemon/mgr/progress/progress_manager.go
Labels: kind/bug, size/S

#498 feature: add mock mgr for the convenience of testing
  hack/generate-super-mock-mgr.sh
  supernode/daemon/mgr/mock/mock_cdn_mgr.go
  supernode/daemon/mgr/mock/mock_dfget_task_mgr.go
  supernode/daemon/mgr/mock/mock_peer_mgr.go
  supernode/daemon/mgr/mock/mock_progress_mgr.go
  supernode/daemon/mgr/mock/mock_scheduler_mgr.go
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/vendor.json
Labels: areas/test, kind/feature, size/XXL

#499 feature: implement the scheculer mgr
  common/errors/errors.go
  common/errors/supernode_errors.go
  supernode/config/constants.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/scheduler/manager_test.go
Labels: kind/feature, size/XL

#505 feature: add httpFileLength field for taskInfo
  apis/swagger.yml
  apis/types/task_info.go
Labels: kind/feature, size/S
