Repository dragonflyoss/Dragonfly, pull requests merged in 2019-06, with the labels that each got.

#571 fix: handle redirect at most 20 times
  dfget/core/downloader/p2p_downloader/power_client.go
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/exception/UrlNotReachableException.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/HttpClientUtil.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
Labels: kind/bug, size/XL

#568 bugfix: add locker util and fix thread-unsafe problems for cdn
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/util/count_rw_mutex.go
  supernode/util/locker.go
Labels: kind/bug, size/XL

#575 feature: use util.LockerPool instead of local storage locker
  supernode/store/local_storage.go
Labels: areas/storage, kind/feature, size/M

#457 feature: implement the task mgr for managing the task
  apis/swagger.yml
  apis/types/task_create_request.go
  apis/types/task_info.go
  common/errors/errors.go
  common/errors/supernode_errors.go
  dfget/util/http_util.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_test.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task/manager_util_test.go
  supernode/daemon/mgr/task_mgr.go
  supernode/daemon/util/store.go
  supernode/server/result_info.go
  supernode/server/router.go
  supernode/server/server.go
  supernode/util/range_util.go
  supernode/util/range_util_test.go
Labels: kind/feature, size/XXL

#576 feature: return updateTaskInfo with cdnStatusFailed when http download gets errors
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/reporter.go
Labels: kind/bug, kind/feature, size/S

#577 feature: delete the repo prefix for download home path
  supernode/config/global_variable.go
Labels: kind/feature, size/S

#585 docs: add eleme to adopters
  adopters.md
  docs/images/adoptor_logo/eleme.png
Labels: LGTM, areas/docs, size/XS

#582 feature: handle client error and repair
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/Constants.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/domain/ClientErrorInfo.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/enumeration/ClientErrorType.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/ExecutorsUtil.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/RangeParseUtil.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/rest/controller/PeerController.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/cdn/util/PathUtil.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/lock/LockService.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/BaseClientErrorHandler.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandleService.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandleServiceImpl.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandler.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/FileMd5NotMatchHandler.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/FileNotExistHandler.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/timer/DataGcService.java
Labels: kind/bug, kind/feature, size/XL

#583 feature: dfget reports client error to supernode
  common/constants/dfget_super_code.go
  dfget/core/api/supernode_api.go
  dfget/core/api/supernode_api_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/helper/test_helper.go
  dfget/types/client_error_request.go
Labels: kind/bug, kind/feature, size/L

#587 feature: dfget reports client error to supernode
  dfget/config/constants.go
  dfget/core/api/supernode_api.go
  dfget/core/api/supernode_api_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/helper/test_helper.go
  dfget/types/client_error_request.go
Labels: kind/bug, kind/feature, size/L

#588 docs: add caicloud as adopter
  README.md
  adopters.md
  docs/images/adoptor_logo/caicloud.png
Labels: LGTM, areas/docs, size/XS

#586 feature: parse the port of supernode from --node flag of dfget
  cmd/dfget/app/root.go
  common/util/net_util.go
  common/util/net_util_test.go
  dfget/config/constants.go
  dfget/core/api/supernode_api.go
  dfget/core/core.go
  dfget/core/regist/register.go
  test/cli_dfget_p2p_test.go
  test/environment/env.go
Labels: kind/feature, size/L

#590 feature: parse the port of supernode from --node flag of dfget
  cmd/dfget/app/root.go
  dfget/config/constants.go
  dfget/core/api/supernode_api.go
  dfget/core/core.go
  dfget/core/regist/register.go
  dfget/util/net_util.go
  dfget/util/net_util_test.go
  test/cli_dfget_p2p_test.go
  test/command/cmd.go
  test/environment/env.go
Labels: kind/feature, size/XL

#592 docs: remove useless contents
  docs/user_guide/README.md
  docs/user_guide/download_files.md
  docs/user_guide/install_server.md
  docs/user_guide/supernode_configuration.md
Labels: areas/docs, size/S

#589 feature: update task register header to slice not map
  apis/swagger.yml
  apis/types/task_register_request.go
  common/util/net_util.go
  common/util/net_util_test.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/downloader_test.go
  supernode/server/0.3_bridge.go
Labels: kind/feature, size/L

#598 fix some typos
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/super_writer.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/util/store.go
  supernode/util/range_util.go
Labels: LGTM, areas/typo, kind/bug, size/S

#600 feature: uploader will not automically exit when alivetime is set to <=0
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/uploader.go
Labels: kind/feature, size/S

#601 feature: make the download port configurable
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
Labels: kind/feature, size/S

#605 bugfix: do not use -1 as the basis for successful conversion
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, size/S

#599 feature: add supernode Dockerfile
  Dockerfile
  Dockerfile.supernode
  Makefile
  hack/docker-build.sh
  hack/install.sh
  hack/supernode-nginx.conf
  supernode/server/0.3_bridge.go
Labels: kind/feature, size/XL

#606 bugfix: return http file length as the file length of register resp
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/super_writer.go
  supernode/daemon/mgr/cdn/super_writer_util.go
  supernode/daemon/mgr/task/manager.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
Labels: kind/bug, size/L

#614 feature: add piece length for task md5 file
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/cdn/super_reader.go
  supernode/daemon/mgr/cdn/super_writer_util.go
Labels: kind/feature, size/S

#615 bugfix: do not add the superPID to pieceState
  supernode/daemon/mgr/progress/progress_util.go
Labels: kind/bug, size/XS

#616 feature: store piece md5s with native bytes
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/file_meta_data_test.go
Labels: kind/feature, size/S

#617 bugfix: parse the lastmodified header to timestamp
  common/util/http_util.go
  common/util/net_util.go
  common/util/net_util_test.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/manager.go
Labels: kind/bug, size/M

#618 log: reduce info logs of supernode
  common/util/http_util.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/reporter.go
  supernode/daemon/mgr/cdn/super_reader.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/server/0.3_bridge.go
Labels: areas/log, size/M

#619 fix: send http request with timeout
  common/util/http_util.go
  dfget/core/api/download_api.go
  dfget/core/downloader/back_downloader/back_downloader.go
  supernode/daemon/mgr/cdn/downloader.go
Labels: kind/bug, size/M

#621 bugfix: update the client progress after success to schedule
  supernode/daemon/mgr/mock/mock_progress_mgr.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
Labels: kind/bug, size/M

#620 bugfix: increase load of the peer serving for others
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
Labels: kind/bug, size/M

#622 doc: update quick start
  docs/images/quick-start-topo.png
  docs/quick_start/README.md
  docs/user_guide/multi_machines_deployment.md
Labels: areas/docs, size/XL

#623 doc: update doc because update 0.3 to 0.4
  FAQ.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
Labels: areas/docs, size/L

#607 test: add unit tests for dfdaemon/config
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
Labels: areas/test, size/XL

#633 bugfix: fix unit test failure
  supernode/daemon/util/filter.go
Labels: areas/test, kind/bug, size/XS

#629 docs:modify some spelling mistakes in the doc
  FAQ.md
Labels: LGTM, areas/docs, size/M

#635 upgrade: bump to Go 1.12.6
  .circleci/config.yml
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.supernode
  docs/user_guide/install_server_go.md
  hack/build.sh
  test/README.md
Labels: size/S
