Repository dragonflyoss/Dragonfly, pull requests merged in 2019-05, with the labels that each got.

#514 feature: add setter/getter about pieces MD5 for task interface
  supernode/daemon/mgr/task_mgr.go
Labels: kind/feature, size/XS

#516 docs: add CII for project to add CII Best Practices Badge
  README.md
Labels: areas/docs, areas/test, size/XS

#517 docs: add more adopters of Dragonfly
  adopters.md
  docs/images/adoptor_logo/huawei.jpg
  docs/images/adoptor_logo/jfrog.png
  docs/images/adoptor_logo/sunus.png
  docs/images/adoptor_logo/zte.png
Labels: areas/docs, size/S

#512 bugfix: update the implementation of local storage
  supernode/store/errors.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/storage_driver.go
  supernode/store/store.go
Labels: areas/storage, kind/bug, size/XL

#519 fix: fix ineffectual assignments
  common/util/http_util_test.go
  dfget/core/core.go
  dfget/core/uploader/peer_server_executor.go
  dfget/util/http_util.go
  supernode/daemon/mgr/dfgettask/manager_test.go
  supernode/daemon/mgr/peer/manager_test.go
  supernode/daemon/mgr/scheduler/manager.go
Labels: LGTM, kind/bug, size/S

#521 docs: correct some abused phrase
  FAQ.md
Labels: LGTM, areas/docs, size/XS

#501 Update documentation for the new transparent proxy
  FAQ.md
  docs/user_guide/proxy.md
Labels: areas/docs, size/L

#459 feature: add AdvertiseIP flag for supernode
  cmd/supernode/app/root.go
  common/util/net_util.go
  supernode/config/config.go
Labels: kind/feature, size/M

#515 feature: add a function to determine whether the resource has expired
  common/util/http_util.go
Labels: kind/feature, size/M

#502 feature: register the supernode as a peer before starting the server
  cmd/supernode/app/root.go
  supernode/config/config.go
  supernode/daemon/daemon.go
Labels: kind/feature, size/M

#529 feature: implement function of IsSuperCID and IsSuperPID
  supernode/config/config.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/daemon/mgr/progress/progress_util_test.go
Labels: areas/test, kind/feature, size/M

#528 bugfix: use advertise-ip as the supernode ip when specified
  cmd/supernode/app/root.go
Labels: areas/test, kind/bug, size/S

#530 feature: use bucket as the parent sub dir of key
  supernode/store/errors.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/store.go
Labels: kind/feature, size/M

#532 feature: add function GetAsString for SyncMap
  common/util/sync_map_util.go
Labels: kind/feature, size/S

#523 [feature] hijack https requests with self-signed certificates
  .gitignore
  Makefile
  cmd/dfdaemon/app/root.go
  dfdaemon/config/config.go
  dfdaemon/handler/transport.go
  dfdaemon/proxy/proxy.go
  dfdaemon/proxy/proxy_test.go
Labels: kind/feature, size/XL

#539 Fixed typos
  cmd/dfdaemon/app/options/options.go
  cmd/dfget/app/root.go
  docs/cli_reference/dfdaemon.md
  docs/cli_reference/dfget.md
Labels: LGTM, areas/typo, size/XS

#547 Update Dockerfile for better caching
  Dockerfile
Labels: size/XS

#548 Configure InsecureSkipVerify for proxied https host
  dfdaemon/config/config.go
  dfdaemon/proxy/proxy.go
  docs/user_guide/proxy.md
Labels: size/S

#533 feaeture: add function GetCIDByPeerIDAndTaskID for dfgetTask
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/mgr/mock/mock_dfget_task_mgr.go
Labels: areas/test, size/S

#552 logs: add some debug logs with progress mgr for better debug
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_util.go
Labels: areas/log, kind/bug, size/S

#554 feature: update scheduler manager GetSuperPID
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/peer/manager_test.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/scheduler/manager_test.go
  supernode/daemon/mgr/scheduler_mgr.go
Labels: kind/feature, size/S

#555 docs: get all dfget logs of a task in dfclient.log
  FAQ.md
  README.md
  docs/images/df-dev-dingtalk.png
Labels: areas/docs, areas/log, size/S

#557 docs: add three adopters into project
  adopters.md
  docs/images/adoptor_logo/autohome.png
  docs/images/adoptor_logo/qichedasheng.png
  docs/images/adoptor_logo/wise2c.png
Labels: areas/docs, size/XS

#561 fix: BackDownloader only download file when response is less than 400
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
Labels: kind/bug, size/S

#562 bugfix: update the response code number
  common/constants/dfget_super_code.go
Labels: kind/bug, size/S

#560 feature: store mgr return localStorage as default StorageDriver
  supernode/store/local_storage_test.go
  supernode/store/store_mgr.go
Labels: areas/storage, kind/feature, size/M

#508 feature: implement the cdn manager
  common/util/http_util.go
  common/util/http_util_test.go
  common/util/limit_reader.go
  common/util/string_util.go
  common/util/string_util_test.go
  supernode/config/config.go
  supernode/config/constants.go
  supernode/config/global_variable.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/cdn_util.go
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/downloader_test.go
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/file_meta_data_test.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/path_util.go
  supernode/daemon/mgr/cdn/piece_md5_mgr.go
  supernode/daemon/mgr/cdn/piece_md5_mgr_test.go
  supernode/daemon/mgr/cdn/reporter.go
  supernode/daemon/mgr/cdn/super_reader.go
  supernode/daemon/mgr/cdn/super_writer.go
  supernode/daemon/mgr/cdn/super_writer_test.go
  supernode/daemon/mgr/cdn/super_writer_util.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/mock/mock_cdn_mgr.go
  vendor/github.com/prashantv/gostub/CHANGELOG.md
  vendor/github.com/prashantv/gostub/LICENSE.md
  vendor/github.com/prashantv/gostub/README.md
  vendor/github.com/prashantv/gostub/README.md.tmpl
  vendor/github.com/prashantv/gostub/doc.go
  vendor/github.com/prashantv/gostub/env.go
  vendor/github.com/prashantv/gostub/gostub.go
  vendor/github.com/prashantv/gostub/version.go
  vendor/vendor.json
Labels: kind/feature, size/XXL

#551 feature: add download port flag
  cmd/supernode/app/root.go
  supernode/config/config.go
  supernode/daemon/daemon.go
Labels: kind/feature, size/S

#563 feature: add GetHTTPPath function for cdn mgr
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/mock/mock_cdn_mgr.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
Labels: kind/feature, size/S

#536 feature: add dfdaemon.Server
  cmd/dfdaemon/app/options/options.go
  cmd/dfdaemon/app/root.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/handler/debug_handler.go
  dfdaemon/handler/env_handler.go
  dfdaemon/handler/param_handler.go
  dfdaemon/handler/root_handler.go
  dfdaemon/initializer/initializer.go
  dfdaemon/muxconf/muxconf.go
  dfdaemon/muxconf/muxconf_test.go
  dfdaemon/proxy/proxy.go
  dfdaemon/server.go
  dfdaemon/transport/transport.go
Labels: kind/feature, size/XXL

#567 feature: backport the feature of supporting https proxy to 0.3.x
  .gitignore
  FAQ.md
  Makefile
  cmd/dfdaemon/app/options/options.go
  cmd/dfdaemon/app/root.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/handler/debug_handler.go
  dfdaemon/handler/env_handler.go
  dfdaemon/handler/param_handler.go
  dfdaemon/handler/root_handler.go
  dfdaemon/initializer/initializer.go
  dfdaemon/muxconf/muxconf.go
  dfdaemon/muxconf/muxconf_test.go
  dfdaemon/proxy/proxy.go
  dfdaemon/proxy/proxy_test.go
  dfdaemon/server.go
  dfdaemon/transport/transport.go
  docs/user_guide/proxy.md
Labels: kind/feature, size/XXL

#566 bugfix: use a public limiter for cdn manager
  common/util/limit_reader.go
  supernode/daemon/mgr/cdn/downloader_test.go
  supernode/daemon/mgr/cdn/manager.go
Labels: kind/bug, size/S

#569 bugfix: calculate realHTTPFileLength which is different realFileLength
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/super_writer.go
  supernode/daemon/mgr/cdn/super_writer_test.go
  supernode/daemon/mgr/progress/progress_util.go
Labels: kind/bug, size/M

#572 fix typo: suernode -> supernode
  docs/design/design.md
Labels: LGTM, areas/typo, size/XS
