Repository dragonflyoss/Dragonfly, pull requests merged in 2019-11, with the labels that each got.

#1021 feature: add weight for node config
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/config/constants.go
  dfget/config/supernode_value.go
  dfget/config/supernode_value_test.go
  docs/config/dfget_config_template.yml
  docs/config/dfget_properties.md
  pkg/algorithm/algorithm.go
  pkg/algorithm/algorithm_test.go
Labels: kind/feature, size/XL

#1052 Using path/filepath instead of path for file operations
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer_test.go
  dfget/core/helper/test_helper.go
  dfget/core/uploader/peer_server_executor_test.go
  dfget/core/uploader/uploader_util_test.go
  pkg/fileutils/fileutils_test.go
  supernode/config/config_test.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/store_mgr.go
Labels: size/XL

#1041 dfdaemon: specify context when invokes dfget
  dfdaemon/downloader/dfget/dfget.go
  dfdaemon/downloader/downloader.go
  dfdaemon/transport/transport.go
Labels: areas/test, size/S

#1057 docs: delete Yum China as a Dragonfly adopter
  adopters.md
Labels: LGTM, areas/docs, size/XS

#1063 fix comment for localStorage
  supernode/store/local_storage.go
Labels: areas/storage, size/XS

#1066 bugfix:modify the comment
  supernode/config/config.go
Labels: kind/bug, size/XS

#1064 chore: Add go mod cache in circleci
  .circleci/config.yml
Labels: chore, size/S

#1049 feature: prohibit the IPv6 to communicate with supernode
  pkg/httputils/http_util.go
  pkg/httputils/http_util_test.go
Labels: kind/feature, size/XS

#1056 bugfix: support truncate the file when put
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/path_util.go
  supernode/daemon/mgr/cdn/reporter.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/storage_driver.go
Labels: kind/bug, size/L

#1068 feature: try to download from back source even if download timeout with dragonfly
  dfget/core/core.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/feature, size/M

#942 feature:registry mirror support direct param.
  dfdaemon/config/config.go
  dfdaemon/proxy/proxy.go
  dfdaemon/proxy/proxy_test.go
  dfdaemon/transport/transport.go
Labels: kind/feature, size/M

#1050 feature: support init from environment variables for dfdaemon and supernode
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/app/root_test.go
  cmd/supernode/app/root.go
  cmd/supernode/app/root_test.go
Labels: kind/feature, size/M

#1076 feature: prohibit the IPv6 addr for supernode peer IP
  pkg/netutils/netutils.go
Labels: kind/feature, size/XS

#1045 bugfix: avoid creating dup-process of dfget server.
  dfget/core/uploader/peer_server_executor.go
  pkg/fileutils/filelock.go
  pkg/fileutils/filelock_test.go
Labels: kind/bug, size/XL

#1071 feat(dfdaemon): add redirect to proxy rule
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/proxy/proxy.go
  dfdaemon/proxy/proxy_test.go
Labels: size/M

#1075 feature: add context for dfget downloader
  dfget/core/core.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/target_writer.go
Labels: kind/feature, size/M

#1081 bugfix: fix running piece concurrent update wrong
  supernode/daemon/mgr/progress/progress_util.go
Labels: kind/bug, size/XS

#1080 feature: make the log related parameter can be configured
  cmd/dfdaemon/app/init.go
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
  dfdaemon/config/config.go
  dfget/config/config.go
  pkg/dflog/log.go
  pkg/dflog/log_test.go
  supernode/config/config.go
Labels: areas/log, kind/feature, size/M

#1077 add goreleaser in circleci
  .circleci/config.yml
  .goreleaser.yml
Labels: areas/CI, areas/test, size/L

#1085 refactor: handle errors gracefully
  dfget/core/core.go
  supernode/daemon/mgr/gc/gc_task.go
  supernode/daemon/mgr/mock/mock_progress_mgr.go
  supernode/daemon/mgr/progress/progress_delete.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
Labels: kind/bug, kind/refactor, size/M

#1087 bugfix: lock file before check server port
  dfget/core/uploader/peer_server_executor.go
Labels: kind/bug, size/XS

#1089 bugfix: the timeout specified by user should be used firstly
  dfget/config/constants.go
  dfget/core/core.go
  dfget/core/downloader/downloader.go
Labels: areas/test, kind/bug, size/S

#1088 optimize: reduce the waiting time for starting dfget server
  dfget/core/uploader/peer_server_executor.go
  dfget/core/uploader/uploader.go
Labels: size/M

#1100 [feature]: add generate doc cmd for supernode
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/gen_doc.go
  cmd/dfget/app/root.go
  cmd/supernode/app/root.go
  hack/generate-docs.sh
  pkg/cmd/gen_doc.go
Labels: kind/feature, size/L

#1102 bugfix: disable displaying auto generation tag in cli docs for supernode
  cmd/supernode/app/root.go
Labels: kind/bug, size/S
