Repository dragonflyoss/Dragonfly, pull requests merged in 2019-12, with the labels that each got.

#1099 fix the "index out of range" error when the length of speed is 0.
  pkg/netutils/netutils.go
Labels: kind/bug, size/XS

#1107 fix broken grafana dashboard
  docs/user_guide/dragonfly.json
Labels: size/XS

#1113 bugfix:fix api response status code
  apis/swagger.yml
Labels: LGTM, kind/bug, size/XS

#1110 cleanup unused scripts and Makefile
  Makefile
  hack/check-docker.sh
  hack/check.sh
Labels: LGTM, size/M

#1114 feature:modify client api
  client/interface.go
  client/peer_create.go
  client/peer_delete.go
  client/peer_info.go
  client/peer_list.go
  client/preheat_create.go
  client/preheat_info.go
  client/task_create.go
  client/task_info.go
Labels: kind/feature, size/M

#1121 fix: unset the default value of totallimit
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/config/constants.go
Labels: kind/bug, size/XS

#1127 [chore] fix bad link
  FAQ.md
Labels: size/XS

#1125 feature: add the yamlint tool to check check all yaml files
  .circleci/config.yml
  .golangci.yml
  .goreleaser.yml
  .travis.yml
  apis/swagger.yml
  docs/config/dfdaemon_config_template.yml
  docs/config/dfget_config_template.yml
  docs/config/supernode_config_template.yml
Labels: LGTM, kind/feature, size/XXL

#1133 bugfix:modify the words spelling mistakes
  dfget/core/downloader/p2p_downloader/.p2p_downloader.go.swn
  pkg/errortypes/supernode_errors.go
  supernode/daemon/mgr/cdn/super_reader.go
Labels: areas/typo, kind/bug, size/XS

#1134 bugfix:Improve the readability of code
  dfget/core/downloader/p2p_downloader/.p2p_downloader.go.swn
  pkg/errortypes/errortypes.go
  pkg/errortypes/supernode_errors.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/task/manager_util.go
Labels: LGTM, kind/bug, size/S

#1148 test: add unit test case for func TransRate
  pkg/ratelimiter/ratelimiter_test.go
Labels: areas/test, size/S

#1084 feature: add 'config default' command to print the default configuration of components
  cmd/dfdaemon/app/root.go
  cmd/supernode/app/root.go
  pkg/cmd/config.go
  pkg/printer/printer.go
Labels: areas/cli, kind/feature, size/L

#1065 feature:modify supernode 1.0 bridge
  apis/swagger.yml
  supernode/server/router.go
  supernode/server/task_bridge.go
Labels: kind/feature, size/M
