Repository dragonflyoss/Dragonfly, pull requests merged in 2019-09, with the labels that each got.

#874 delete ertra spaces
  .github/ISSUE_TEMPLATE/feature-request-of-dragonfly.md
  CONTRIBUTING.md
Labels: LGTM, size/XS

#743 feature: add tasks create actions in client pkg of golang sdk
  client/task_create.go
Labels: LGTM, kind/feature, size/S

#876 Modify the Chinese punctuation mark to the English punctuation mark
  CONTRIBUTING.md
  cmd/supernode/app/version.go
  docs/quick_start/README.md
  docs/user_guide/multi_machines_deployment.md
  test/README.md
Labels: LGTM, size/S

#877 Modify the Chinese punctuation mark to the English punctuation mark
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/uploader/uploader_util.go
Labels: size/XS

#815 bugfix: add timeout for download piece
  cmd/dfget/app/server.go
  dfget/config/constants.go
  dfget/core/api/download_api.go
  dfget/core/core.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/uploader/peer_server_executor.go
  dfget/core/uploader/peer_server_executor_test.go
  pkg/fileutils/fileutils_test.go
  pkg/httputils/http_util.go
  pkg/httputils/http_util_test.go
  pkg/netutils/netutils.go
  pkg/netutils/netutils_test.go
  pkg/queue/queue_test.go
  pkg/ratelimiter/ratelimiter_test.go
  pkg/stringutils/stringutils_test.go
  pkg/syncmap/syncmap_test.go
  supernode/config/config.go
  supernode/config/constants.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, size/XL

#819 feature: limit the number which download from supernode for one task
  supernode/config/config.go
  supernode/daemon/mgr/mock/mock_progress_mgr.go
  supernode/daemon/mgr/progress/progress_delete.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/progress/progress_state.go
  supernode/daemon/mgr/progress/state_sync_map.go
  supernode/daemon/mgr/progress/superload_manager.go
  supernode/daemon/mgr/progress_mgr.go
  supernode/daemon/mgr/scheduler/manager.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/feature, size/XL

#851 bugfix: modify gc logic err
  supernode/daemon/mgr/gc/gc_peer.go
Labels: kind/bug, size/XS

#882 delete os.O_SYNC flag when supernode write piece to local
  supernode/store/local_storage.go
Labels: size/XS

#883 feature: add some cdn metrics
  docs/user_guide/metrics.md
  supernode/daemon/mgr/cdn/downloader_test.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/task/manager.go
  supernode/server/server.go
Labels: areas/monitoring, kind/feature, size/M

#885 feature: add gc cli config
  cmd/supernode/app/root.go
Labels: kind/feature, size/S

#829 feature: add supernode piece downloaded size metrics
  docs/user_guide/metrics.md
  supernode/server/0.3_bridge.go
  supernode/server/metrics.go
  supernode/util/range_util.go
  supernode/util/range_util_test.go
Labels: kind/feature, size/L

#906 bugfix:fix the gc time
  supernode/daemon/mgr/gc/gc_peer.go
Labels: kind/bug, size/XS

#907 bugfix:fix dfget panic
  dfget/core/core.go
Labels: kind/bug, kind/panic, priority/P1, size/XS

#890 feature: make supernode compatible with the 0.2.x dfget
  go.mod
  go.sum
  supernode/server/0.3_bridge.go
Labels: kind/feature, size/S

#911 fix typo in /dfget/core/uploader/
  dfget/core/uploader/uploader.go
Labels: areas/typo, size/XS

#916 improve standard of the document
  pkg/errortypes/errortypes.go
  pkg/errortypes/supernode_errors.go
  pkg/printer/printer.go
  pkg/syncmap/syncmap.go
Labels: areas/docs, size/S

#918 perfect the document
  supernode/config/config.go
  supernode/daemon/daemon.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/piece_md5_mgr.go
  supernode/daemon/mgr/dfgettask/manager.go
  supernode/daemon/util/filter.go
Labels: areas/docs, size/S

#919 docs: fix wrong command.
  docs/user_guide/install_server.md
Labels: areas/cli, areas/docs, kind/bug, size/XS

#920 modify document
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/dfget_task_mgr.go
  supernode/daemon/mgr/gc/gc_manager.go
  supernode/daemon/mgr/peer/manager.go
  supernode/daemon/mgr/progress/progress_util.go
  supernode/httpclient/origin_http_client.go
  supernode/plugins/plugin_manager.go
  supernode/plugins/plugins.go
  supernode/server/result_info.go
  supernode/store/errors.go
  supernode/store/local_storage.go
  supernode/store/storage_driver.go
  supernode/store/store.go
  supernode/store/store_mgr.go
  test/command/cmd.go
  test/request/request.go
Labels: areas/docs, size/M

#881 feature: support rate type
  cmd/dfdaemon/app/init.go
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/supernode/app/root.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/proxy/proxy.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/config/constants.go
  dfget/core/core_test.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_executor.go
  go.sum
  pkg/limitreader/limit_reader.go
  pkg/netutils/netutils.go
  pkg/netutils/netutils_test.go
  pkg/rate/rate.go
  pkg/rate/rate_test.go
  pkg/ratelimiter/ratelimiter.go
  supernode/config/config.go
  supernode/daemon/mgr/cdn/manager.go
Labels: kind/feature, kind/refactor, size/XXL

#926 log: not rotate log file when startup
  cmd/dfdaemon/app/init.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  pkg/dflog/log.go
Labels: areas/log, size/S

#923 perfect document
  client/client.go
  client/preheat_info.go
  cmd/dfdaemon/app/gen_doc.go
  cmd/dfdaemon/app/init.go
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/gen_doc.go
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
Labels: areas/docs, size/S

#924 cmd: add err handling
  cmd/dfdaemon/app/root_test.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
Labels: size/S

#915 test: add err handling in test
  test/cli_dfget_p2p_test.go
Labels: areas/test, size/XS

#932 feature: use constant value to replace literals in supernode config.
  supernode/config/config.go
  supernode/config/constants.go
  supernode/daemon/mgr/scheduler/manager.go
Labels: kind/feature, size/M

#930 Remove useless return value of gc task function
  supernode/daemon/mgr/gc/gc_task.go
Labels: size/XS

#940 Grammatical correction
  client/client.go
  dfdaemon/proxy/proxy.go
  dfget/config/config.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
Labels: size/S

#935 dfget: add err handling
  dfget/config/config_test.go
  dfget/config/metadata_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
Labels: size/S

#914 fix(client): add error handling in client
  client/peer_delete.go
  client/request.go
  client/task_delete.go
  client/task_update.go
  client/utils.go
Labels: kind/bug, size/S

#941 fix typo
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/piece_error_mgr.go
  supernode/daemon/mgr/progress/progress_manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task_mgr.go
  supernode/daemon/util/filter.go
Labels: areas/typo, size/S

#931 feature: add gc metrics
  docs/user_guide/metrics.md
  supernode/daemon/mgr/gc/gc_manager.go
  supernode/daemon/mgr/gc/gc_peer.go
  supernode/daemon/mgr/gc/gc_task.go
  supernode/server/server.go
Labels: areas/monitoring, kind/feature, size/M

#888 bugfix:gc peer failing to server down
  supernode/daemon/mgr/gc/gc_dfget_task.go
  supernode/daemon/mgr/gc/gc_peer.go
Labels: kind/bug, size/S

#947 Adjust the word order of comments
  cmd/supernode/app/options.go
  dfdaemon/config/config.go
  dfdaemon/constant/constant.go
  dfdaemon/proxy/proxy.go
  dfdaemon/server.go
  dfdaemon/transport/transport.go
Labels: size/S

#878 feature: add supernode disk gc feature
  cmd/supernode/app/root.go
  go.mod
  go.sum
  pkg/errortypes/errortypes.go
  pkg/fileutils/filesize.go
  pkg/fileutils/filesize_test.go
  pkg/fileutils/fileutils.go
  supernode/config/config.go
  supernode/config/constants.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/cdn_gc.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/path_util.go
  supernode/daemon/mgr/cdn_mgr.go
  supernode/daemon/mgr/gc/gc_disk.go
  supernode/daemon/mgr/gc/gc_manager.go
  supernode/daemon/mgr/mock/mock_cdn_mgr.go
  supernode/daemon/mgr/task/manager.go
  supernode/store/local_storage.go
  supernode/store/storage_driver.go
  supernode/store/store.go
Labels: kind/feature, size/XXL

#956 Add docs about other exporters
  docs/user_guide/monitoring.md
Labels: areas/docs, size/XS

#948 doc: add instructions how to join Dragonfly as a meber
  CONTRIBUTING.md
  FAQ.md
Labels: areas/docs, kind/question, size/S

#929 bugfix: paas registry mirror tls config into dfget config.
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
Labels: kind/bug, size/M

#937 feature: add 'help' target to Makefile and make it the default
  Makefile
Labels: kind/feature, size/M

#903 fix: ineffective viper alias
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/app/root_test.go
Labels: kind/bug, size/L

#961 cleanup code base: reformat some code based on staticcheck
  client/request.go
  dfget/core/core.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/uploader.go
  supernode/server/router.go
Labels: LGTM, size/S

#951 fix(supernode/server): add error handling
  supernode/server/0.3_bridge.go
  supernode/server/router_test.go
  supernode/server/system_bridge.go
Labels: areas/test, kind/bug, size/S

#963 docs: update the metrics as a table
  docs/user_guide/metrics.md
Labels: areas/docs, size/M

#968 Improve the comments: modify the words spelling mistakes
  cmd/dfdaemon/app/root.go
  dfget/core/uploader/uploader.go
Labels: size/XS

#965 fix(version) : add some punctuation
  .gitignore
  version/version.go
Labels: size/S

#972 docs: update stale metrics docs
  docs/user_guide/metrics.md
Labels: areas/docs, size/XS

#967 clinte, dfget, supernode: delete unused functions based on static check
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_util_test.go
  supernode/daemon/mgr/progress/state_sync_map.go
Labels: size/S

#966 feature: add gc disks metrics
  docs/user_guide/metrics.md
  supernode/config/config.go
  supernode/daemon/mgr/gc/gc_disk.go
  supernode/daemon/mgr/gc/gc_manager.go
Labels: kind/feature, size/S

#960 bugfix: reduce error logs when download home dir not exist
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/cdn/cdn_gc.go
  supernode/store/local_storage.go
Labels: areas/log, kind/bug, size/S

#969 pkg, supernode: cleanup code based on static check warning
  pkg/util/assert.go
  supernode/daemon/mgr/cdn/cdn_gc.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/cdn/reporter.go
Labels: LGTM, size/S

#974 fix(supernode/config): add error handling
  supernode/config/config_test.go
Labels: kind/bug, size/S

#954 docs:add FAQ.md abot how dfget connect to supernodes in mul-supernode mode
  FAQ.md
Labels: areas/docs, size/XS

#909 feature:make cli better
  cmd/dfget/app/root.go
  cmd/dfget/app/server.go
  cmd/supernode/app/root.go
  cmd/supernode/app/root_test.go
Labels: kind/feature, size/M

#902 feature: add grafana dashboard
  docs/images/dashboards/dashboard1.png
  docs/images/dashboards/dashboard2.png
  docs/user_guide/dragonfly.json
  docs/user_guide/monitoring.md
Labels: areas/monitoring, kind/feature, size/XXL

#936 make the struct Properties embedded into config Ref#933
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/config/constants.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/core/regist/register.go
  dfget/core/regist/register_test.go
Labels: size/L
