Repository dragonflyoss/Dragonfly, pull requests merged in 2019-03, with the labels that each got.

#432 Fix some misspells
  apis/swagger.yml
  apis/types/peer_info.go
  docs/api_reference/apis.md
Labels: size/XS

#277 fix: unreachable supernode ip in p2p-network
  docs/quick_start/README.md
  src/supernode/src/main/docker/Dockerfile
  src/supernode/src/main/docker/sources/start.sh
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
Labels: areas/network, kind/bug, size/M, supernode-Java

#429 test: implements test/command package of integration testing
  .circleci/config.yml
  dfget/core/downloader/p2p_downloader/power_client.go
  src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/ClusterMember.java
  test/README.md
  test/cli_dfget_p2p_test.go
  test/command/cmd.go
Labels: areas/cli, areas/test, kind/feature, size/XL

#436 refactor: Extract the common utils to the common folder
  cmd/dfget/app/root.go
  cmd/dfget/app/root_test.go
  cmd/dfget/app/server.go
  common/dflog/log.go
  common/dflog/log_test.go
  common/util/assert.go
  common/util/assert_test.go
  common/util/file_util.go
  common/util/file_util_test.go
  common/util/limit_reader.go
  common/util/net_util.go
  common/util/net_util_test.go
  common/util/rate_limiter.go
  common/util/rate_limiter_test.go
  dfdaemon/handler/root_handler.go
  dfdaemon/initializer/initializer.go
  dfdaemon/util/urlutil.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/back_downloader/back_downloader_test.go
  dfget/core/downloader/downloader.go
  dfget/core/downloader/downloader_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/client_writer_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/piece.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/downloader/p2p_downloader/target_writer.go
  dfget/core/helper/test_helper.go
  dfget/core/regist/register.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader_helper_test.go
  dfget/core/uploader/uploader_test.go
  dfget/util/algorithm_test.go
  dfget/util/http_util.go
  dfget/util/queue.go
  dfget/util/queue_test.go
  dfget/util/std_printer.go
Labels: kind/refactor, size/XL

#438 feature: add some utils that supernode will use
  common/util/assert.go
  common/util/assert_test.go
  common/util/digest_util.go
  common/util/file_util.go
  common/util/net_util.go
  common/util/net_util_test.go
  dfget/config/config.go
  dfget/config/config_test.go
  dfget/core/core.go
  dfget/core/core_test.go
  supernode/util/range_util.go
  supernode/util/range_util_test.go
Labels: kind/feature, size/XL

#442 doc: update the version of dfclient to v0.3.0
  docs/quick_start/README.md
  docs/user_guide/download_files.md
  docs/user_guide/install_client.md
Labels: areas/docs, size/M

#444 Fix some typos in code
  apis/swagger.yml
  apis/types/preheat_create_request.go
  apis/types/task_create_request.go
  apis/types/task_info.go
  docs/api_reference/apis.md
Labels: areas/typo, size/S

#448 fix supernode default port doc
  docs/user_guide/supernode_configuration.md
Labels: size/XS

#440 refactor: extract the common const code to the common folder
  common/constants/dfget_super_code.go
  dfget/config/constants.go
  dfget/core/api/supernode_api_test.go
  dfget/core/core.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/piece.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/helper/test_helper.go
  dfget/core/regist/register.go
  dfget/core/regist/register_test.go
  dfget/types/pull_piece_task_response.go
  dfget/types/types_test.go
Labels: kind/refactor, size/XL

#446 feature: add storage driver for supernode
  common/util/file_util.go
  common/util/stat_darwin_amd64.go
  common/util/stat_linux_amd64.go
  dfdaemon/initializer/initializer.go
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/storage_driver.go
  supernode/store/store.go
  supernode/store/store_mgr.go
Labels: areas/storage, kind/feature, size/XXL

#452 ensuring Go interface satisfaction at compile-time
  dfdaemon/downloader/dfget/dfget.go
  dfget/core/api/download_api.go
  dfget/core/api/supernode_api.go
  dfget/core/api/uploader_api.go
  dfget/core/downloader/back_downloader/back_downloader.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/regist/register.go
  dfget/core/uploader/peer_server_executor.go
  dfget/util/http_util.go
  dfget/util/queue.go
Labels: size/S

#455 bugfix: add context for the interface of storage driver
  supernode/store/local_storage.go
  supernode/store/local_storage_test.go
  supernode/store/storage_driver.go
  supernode/store/store.go
Labels: areas/storage, kind/bug, size/L

#453 feature: implement the peer mgr
  apis/swagger.yml
  apis/types/peer_info.go
  common/util/assert.go
  common/util/assert_test.go
  supernode/daemon/daemon.go
  supernode/daemon/mgr/filter.go
  supernode/daemon/mgr/filter_test.go
  supernode/daemon/mgr/peer_mgr.go
  supernode/daemon/mgr/peer_mgr_test.go
  supernode/daemon/mgr/store.go
  supernode/daemon/mgr/store_test.go
  supernode/errors/errors.go
  supernode/result/result_info.go
  supernode/server/peer_bridge.go
  supernode/server/router.go
  supernode/server/server.go
Labels: kind/feature, size/XXL
