Repository dragonflyoss/Dragonfly, pull requests merged in 2019-07, with the labels that each got.

#642 docs:modify a mistake in the doc
  docs/user_guide/install_server_go.md
Labels: LGTM, areas/docs, size/XS

#641 docs: fix some typos and grammar issue
  CONTRIBUTING.md
  README.md
Labels: LGTM, areas/docs, areas/typo, size/XS

#653 docs:modify some spell mistakes in the document
  docs/design/design.md
Labels: LGTM, areas/docs, size/S

#649 fix: unit-test failed in file_util_test.go caused by user permission
  common/util/file_util_test.go
Labels: areas/test, kind/bug, size/S

#657 chore: update pouchlinter
  .circleci/config.yml
  CONTRIBUTING.md
  common/util/net_util_test.go
  hack/generate-swagger-models.sh
Labels: size/S

#663 bugfix: update Dockerfile of supernode
  Dockerfile.supernode
  hack/start-supernode.sh
Labels: kind/bug, size/XS

#664 feature: implement minrate option for dfget when downloading a file
  cmd/dfget/app/root.go
  dfget/config/config.go
  dfget/config/constants.go
  dfget/core/core.go
Labels: kind/feature, size/S

#654 [refactor] refact pprof and add test for supernode router
  dfdaemon/handler/root_handler.go
  dfdaemon/handler/version_handler.go
  supernode/server/router.go
  supernode/server/router_test.go
Labels: areas/test, kind/refactor, size/L

#666 docs:add a question and answer about the log's time
  FAQ.md
Labels: areas/docs, areas/log, kind/question, size/XS

#645 docs: add --node when starting dfclient container in quick_start docs
  docs/quick_start/README.md
Labels: areas/docs, size/S

#668 bugfix: update supernode Dockerfile
  Dockerfile.supernode
  docs/quick_start/README.md
Labels: kind/bug, size/XS

#667 feature: enable uploader server ip and port to be specified
  cmd/dfget/app/root.go
  dfget/core/core.go
  dfget/core/uploader/peer_server_executor.go
Labels: areas/test, kind/feature, size/S

#671 bugfix: initProperties after trans the param
  cmd/dfget/app/root.go
  dfget/core/core.go
Labels: kind/bug, size/S

#670 feature: pass the value of dfdaemon verbose flag to dfget
  dfdaemon/config/config.go
  dfdaemon/downloader/dfget/dfget.go
Labels: kind/feature, size/XS

#675 bugfix: set GO111MODULE to on when use docker build
  cmd/supernode/app/root.go
  hack/build.sh
Labels: kind/bug, size/S

#639 doc: user guide to use dfdaemon as http proxy for docker
  docs/user_guide/docker_proxy.md
  docs/user_guide/proxy.md
Labels: areas/docs, size/XL

#678 docs: add more adopters for Dragonfly
  adopters.md
  docs/images/adoptor_logo/bilibili.png
  docs/images/adoptor_logo/sogou.jpg
Labels: areas/docs, size/XS

#674 feature: add more version information to both cmd and router
  apis/swagger.yml
  apis/types/df_get_task.go
  apis/types/dragonfly_version.go
  apis/types/error.go
  apis/types/error_response.go
  apis/types/peer_create_request.go
  apis/types/peer_create_response.go
  apis/types/peer_info.go
  apis/types/piece_info.go
  apis/types/piece_pull_request.go
  apis/types/piece_update_request.go
  apis/types/preheat_create_request.go
  apis/types/preheat_create_response.go
  apis/types/preheat_info.go
  apis/types/result_info.go
  apis/types/task_create_request.go
  apis/types/task_create_response.go
  apis/types/task_info.go
  apis/types/task_register_request.go
  apis/types/task_update_request.go
  cmd/dfdaemon/app/root.go
  cmd/dfdaemon/app/version.go
  cmd/dfget/app/version.go
  cmd/supernode/app/version.go
  dfdaemon/handler/root_handler.go
  dfdaemon/handler/version_handler.go
  hack/build.sh
  supernode/server/router.go
  supernode/server/router_test.go
  version/version.go
Labels: LGTM, kind/feature, size/XL

#683 fix type "questiones" -> "questions"
  FAQ.md
Labels: LGTM, kind/question, size/XS

#669 feature: add support for prometheus metrics
  dfdaemon/constant/constant.go
  dfdaemon/handler/root_handler.go
  dfdaemon/server.go
  docs/images/dragonfly_metrics.png
  docs/user_guide/metrics.md
  docs/user_guide/monitoring.md
  go.mod
  go.sum
  supernode/config/constants.go
  supernode/server/metrics.go
  supernode/server/router.go
  supernode/server/router_test.go
  supernode/server/server.go
  test/api_metrics_test.go
  test/api_ping_test.go
  test/cli_dfget_p2p_test.go
  test/request/request.go
  test/util_api.go
  version/version.go
Labels: LGTM, areas/monitoring, kind/feature, size/XL

#700 Add support for arm32
  common/util/stat_linux_arm.go
Labels: size/M

#711 improve docs install_client.md
  docs/user_guide/install_client.md
Labels: LGTM, size/XS

#710 docs: improve docs download_files.md
  docs/user_guide/download_files.md
Labels: LGTM, areas/docs, size/XS

#709 fix type "furthure" -> "further"
  docs/README.md
Labels: LGTM, size/XS

#716 fix typo "caculate" -> "calculate"
  supernode/daemon/mgr/task/manager_util.go
Labels: areas/typo, size/XS

#714 chore: fix script to check code format
  hack/check.sh
Labels: size/XS

#715 bugfix: use rawUrl to interact with source server
  dfdaemon/proxy/proxy.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, size/XS

#719 print help message when check parameter error
  cmd/dfget/app/root.go
Labels: kind/bug, size/S

#707 Add options for bash scripts
  hack/after-install.sh
  hack/before-remove.sh
  hack/build.sh
  hack/check-docker.sh
  hack/check.sh
  hack/docker-build.sh
  hack/env.sh
  hack/generate-contributors.sh
  hack/generate-docs.sh
  hack/generate-super-mock-mgr.sh
  hack/generate-swagger-models.sh
  hack/install.sh
  hack/package.sh
  hack/start-supernode.sh
  hack/unit-test.sh
Labels: size/M

#690 docs: update docs for release 0.4.2
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  docs/quick_start/README.md
  docs/user_guide/docker_proxy.md
  docs/user_guide/install_client.md
  docs/user_guide/install_server.md
  docs/user_guide/install_server_go.md
  docs/user_guide/multi_machines_deployment.md
  docs/user_guide/proxy.md
  docs/user_guide/supernode_configuration.md
Labels: areas/docs, size/XL

#722 fix: markdown-link-check ignore twitter.com
  .circleci/config.yml
Labels: kind/bug, size/XS

#701 feature: return supernode ip according to the value specified by peer
  apis/swagger.yml
  apis/types/df_get_task.go
  apis/types/task_create_request.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/server/0.3_bridge.go
Labels: areas/test, kind/feature, size/M

#726 fix typo 'deisgn' -> 'design'
  docs/README.md
Labels: LGTM, areas/typo, kind/design, size/XS

#717 feature: add callsystem when task create
  apis/swagger.yml
  apis/types/df_get_task.go
  apis/types/task_create_request.go
  apis/types/task_info.go
  apis/types/task_register_request.go
  supernode/daemon/mgr/dfgettask/manager_test.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/daemon/mgr/task/manager_util_test.go
  supernode/server/0.3_bridge.go
Labels: kind/feature, size/XL

#731 fix wrong spells in file_util.go
  common/util/file_util.go
Labels: size/XS

#718 bugfix: use access time to determine whether the file is expired
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/peer_server_test.go
  dfget/core/uploader/uploader_test.go
  supernode/daemon/mgr/cdn/cache_detector.go
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/bug, size/M

#724 bugfix: fix overflow for rate limit
  common/util/assert.go
  common/util/assert_test.go
  common/util/limit_reader.go
  common/util/rate_limiter.go
  common/util/rate_limiter_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  dfget/core/uploader/peer_server.go
  dfget/core/uploader/uploader_helper_test.go
Labels: kind/bug, size/M

#696 docs: add a doc about how to add metrics
  apis/swagger.yml
  cmd/dfdaemon/app/version.go
  cmd/dfget/app/version.go
  cmd/supernode/app/version.go
  common/util/metrics_util.go
  docs/user_guide/monitoring.md
  supernode/config/constants.go
  supernode/server/metrics.go
  test/util_api.go
  version/version.go
Labels: areas/docs, size/XL

#747 docs: improve docs FAQ.md
  FAQ.md
Labels: LGTM, areas/docs, size/S

#736 bugfix: Use a local file instead of a remote file as the url to be downloaded
  Makefile
  test/cli_dfget_p2p_test.go
  test/command/cmd.go
  test/environment/env.go
Labels: kind/bug, size/L

#729 feature: support non-ipv4 format node address for Dragonfly dfclient
  FAQ.md
  apis/swagger.yml
  apis/types/task_register_request.go
  cmd/dfdaemon/app/root.go
  cmd/dfget/app/root.go
  hack/build.sh
  hack/install.sh
  hack/package.sh
  supernode/server/0.3_bridge.go
Labels: kind/feature, size/M

#744 feature: add tasks info actions in client pkg of golang sdk
  client/task_info.go
Labels: LGTM, kind/feature, size/S

#745 feature: add tasks delete actions in client pkg of golang sdk
  client/task_delete.go
Labels: LGTM, kind/feature, size/S

#746 feature: add task update actions in client pkg of golang sdk
  client/request.go
  client/task_update.go
Labels: LGTM, kind/feature, size/M

#754 doc: add new adopters for Dragonfly
  adopters.md
  docs/images/adoptor_logo/ChinaUnicom.png
Labels: areas/docs, size/XS

#748 refactor: make p2p downloader more readable
  common/util/assert.go
  common/util/assert_test.go
  dfget/config/config.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/piece.go
  supernode/daemon/mgr/cdn/file_meta_data.go
  supernode/daemon/mgr/cdn/piece_md5_mgr.go
  supernode/daemon/mgr/cdn/reporter.go
  supernode/daemon/mgr/cdn/super_reader.go
  supernode/daemon/mgr/task/manager_util.go
Labels: kind/refactor, size/L

#682 bugfix: modify two supernode api's bug
  common/constants/dfget_super_code.go
  dfget/core/api/supernode_api.go
  dfget/core/api/supernode_api_test.go
  supernode/server/0.3_bridge.go
Labels: kind/bug, size/M
