Repository dragonflyoss/Dragonfly, pull requests merged in 2020-05, with the labels that each got.

#1318 refactor: move package dfget/util to pkg/algorithm
  cmd/dfdaemon/app/init.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/util/algorithm.go
  dfget/util/algorithm_test.go
  pkg/algorithm/algorithm.go
  pkg/algorithm/algorithm_test.go
Labels: kind/refactor, size/XL

#1294 feature: define the interface SupernodeLocator
  dfget/config/constants.go
  dfget/locator/locator.go
  dfget/locator/static_locator.go
  dfget/locator/static_locator_test.go
Labels: kind/feature, size/XL

#1321 bugfix: infinite loop in dfget/config/config.go#checkOutput
  dfget/config/config.go
  dfget/config/config_test.go
Labels: kind/bug, size/XS

#1326 Proxy: do not log error messages when http Server is closed
  dfdaemon/proxy/proxy.go
Labels: areas/log, kind/bug, size/XS

#1324 refactor: redefine the behavior of SupernodeLocator
  dfget/config/constants.go
  dfget/config/supernode_value.go
  dfget/core/core.go
  dfget/locator/locator.go
  dfget/locator/static_locator.go
  dfget/locator/static_locator_test.go
Labels: kind/refactor, size/M

#1242 feature: define the interface and http api of preheat
  apis/swagger.yml
  apis/types/preheat_create_request.go
  apis/types/preheat_info.go
  apis/types/preheat_status.go
  client/preheat_info_test.go
  supernode/daemon/mgr/preheat/manager.go
  supernode/daemon/mgr/preheat_mgr.go
  supernode/server/preheat_bridge.go
  supernode/server/router.go
  supernode/server/server.go
Labels: LGTM, kind/feature, size/XL

#1313 Supernode support seed task pr
  apis/swagger.yml
  apis/types/heart_beat_response.go
  supernode/server/0.3_bridge.go
  supernode/server/router.go
Labels: areas/supernode-go, size/L

#1340 fix: pass GOPROXY to docker build
  Dockerfile
  Dockerfile.supernode
  hack/docker-build.sh
Labels: kind/bug, size/M

#1330 supernode/config: add some unit tests
  supernode/config/config_test.go
Labels: areas/test, size/S

#1272 Add unit test cases for download_api_test.go&algorithm_test.go&atomiccount_test.go&httpuils_test.go
  client/httpuils_test.go
  dfget/core/api/download_api_test.go
  pkg/atomiccount/atomiccount_test.go
Labels: areas/test, size/M

#1325 refactor: refactor dfget/core with SupernodeLocator
  cmd/dfget/app/root_test.go
  dfget/config/config.go
  dfget/core/core.go
  dfget/core/core_test.go
  dfget/core/regist/register.go
  dfget/core/regist/register_test.go
  dfget/locator/locator.go
  dfget/locator/locator_test.go
  dfget/locator/manager.go
  dfget/locator/static_locator.go
  dfget/locator/static_locator_test.go
Labels: kind/refactor, size/XL

#1348 fix(ci): disable shadow clone in travis-ci
  .travis.yml
Labels: areas/test, size/XS

#1305 define cache for seed file in seed pattern
  dfdaemon/seed/cache.go
  dfdaemon/seed/cache_test.go
  pkg/bitmap/bitmap.go
Labels: size/XXL

#1345 feature: add Select api into SupernodeLocator
  dfget/locator/locator.go
  dfget/locator/static_locator.go
Labels: kind/feature, size/XS

#1343 Feat/reconstruct dfget interface
  dfget/corev2/basic/interface.go
  dfget/corev2/clientwriter/client_writer.go
  dfget/corev2/datascheduler/data_scheduler.go
  dfget/corev2/downloader/downloader.go
  dfget/corev2/regist/register.go
  dfget/corev2/report/reporter.go
  dfget/corev2/uploader/uploader.go
  pkg/protocol/distributiondata.go
  pkg/protocol/url.go
Labels: size/XL

#1351 optimize the HTTPWithHeaders
  pkg/httputils/http_util.go
  pkg/httputils/http_util_test.go
Labels: size/L

#1353 fix: don't delete the parent directory of the task file
  supernode/daemon/mgr/cdn/path_util.go
Labels: kind/bug, size/S

#1355 move some types to basic package
  dfget/corev2/basic/types.go
  dfget/corev2/datascheduler/data_scheduler.go
Labels: size/M

#1358 add schedule peer info
  dfget/corev2/basic/types.go
Labels: size/XS

#1352 Feat/add implementation for dfget interface
  pkg/protocol/http/http.go
  pkg/protocol/http/md.go
  pkg/protocol/http/md_test.go
  pkg/protocol/http/resource.go
  pkg/protocol/http/resource_test.go
  pkg/protocol/url.go
Labels: size/XL

#1346 refactor: define api register of supernode
  supernode/server/api/api.go
  supernode/server/api/api_test.go
  supernode/server/api/handler.go
  supernode/server/api/utils.go
  supernode/server/api/utils_test.go
  supernode/server/router.go
Labels: kind/refactor, size/XL

#1364 update interface of ClientWriter
  dfget/corev2/basic/interface.go
  dfget/corev2/clientwriter/client_writer.go
  dfget/corev2/common/notify.go
Labels: size/L

#1371 fix: replace expired QR-code of dingtalk group
  docs/images/df-dev-dingtalk.png
Labels: kind/bug, size/XS

#1369 test: add unit test case for supernode_value.go
  dfget/config/supernode_value_test.go
Labels: areas/test, size/XS
