Repository dragonflyoss/Dragonfly, pull requests merged in 2020-06, with the labels that each got.

#1368 add functional options for new protocol client
  pkg/protocol/http/http.go
  pkg/protocol/url.go
Labels: size/XL

#1362 add hash circler locator
  dfget/locator/hashcircler_locator.go
  dfget/locator/hashcircler_locator_test.go
  go.mod
  go.sum
  pkg/algorithm/algorithm.go
  pkg/algorithm/algorithm_test.go
  pkg/hashcircler/hash_circler.go
  pkg/hashcircler/hash_circler_test.go
Labels: areas/test, size/XXL

#1385 fix: remove default registry definition in Dockerfile.
  Dockerfile
  docs/config/dfdaemon_config_template.yml
Labels: size/XS

#1386 fix: delete empty directory in local storage
  pkg/fileutils/fileutils.go
  pkg/fileutils/fileutils_test.go
  supernode/daemon/mgr/cdn/path_util.go
  supernode/store/local_storage.go
Labels: areas/storage, kind/bug, size/M

#1381 bugfix: cdn cannot re-download uncompleted task with header param
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/downloader_test.go
  supernode/httpclient/origin_http_client.go
  supernode/httpclient/origin_http_client_test.go
Labels: kind/bug, size/L

#1374 test: add unit test case for static_locator.go
  dfget/locator/static_locator_test.go
Labels: areas/test, size/S

#1383 Fix go-lint warning: "exported method ... should have comment or be unexported"
  dfget/locator/static_locator.go
Labels: size/S

#1382 test: add unit test case for func NewHTTPError
  pkg/errortypes/errortypes_test.go
Labels: areas/test, kind/bug, size/S

#1398 Update docs and example image version
  FAQ.md
  docs/config/README.md
  docs/quick_start/README.md
  docs/user_guide/multi_machines_deployment.md
Labels: size/M

#1404 doc(README): change "Sandbox" to "Incubating"
  README.md
Labels: size/XS
