Repository dragonflyoss/Dragonfly, pull requests merged in 2020-09, with the labels that each got.

#1465 bugfix: dfdaemon does not back to source when download failed by dfget
  dfdaemon/exception/errors.go
  dfdaemon/transport/transport.go
Labels: kind/bug, size/XS

#1466 feature: compare md5 after downloaded
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/feature, size/XS

#1440 add docs for cri-o registry mirror
  docs/README.md
  docs/quick_start/README.md
  docs/user_guide/container_runtimes/README.md
  docs/user_guide/container_runtimes/crio_mirror.md
  docs/user_guide/container_runtimes/docker_proxy.md
Labels: size/L

#1476 change http code from 409 to 208 when create preheat which is already…
  supernode/daemon/mgr/preheat/preheat_service.go
Labels: size/XS

#1478 add jim3ma as a maintainer
  MAINTAINERS.md
Labels: LGTM, size/XS

#1485 bugfix(supernode) the log level default debug
  supernode/daemon/mgr/preheat/file_preaheater.go
Labels: LGTM, areas/log, kind/bug, size/XS

#1461 update supernode metrics
  docs/user_guide/dragonfly.json
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/task/manager.go
  supernode/server/metrics.go
Labels: size/L

#1490 bugfix(dfget) fix panic for slice bounds out of range when sendSuccessPiece
  dfget/core/downloader/p2p_downloader/client_writer.go
Labels: kind/bug, kind/panic, priority/P1, size/XS

#1390 test: add unit test case for hashcircler_locator.go
  dfget/locator/hashcircler_locator_test.go
Labels: areas/test, size/XS

#1384 test: Add unit test for dfget/locator/manager.go
  dfget/locator/manager_test.go
Labels: areas/test, size/L

#1494 bugfix(dfget) finishTask should return error
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/bug, size/XS
