Repository dragonflyoss/Dragonfly, pull requests merged in 2020-07, with the labels that each got.

#1366 refactor: use package server/api to register supernode's API
  supernode/server/api/api.go
  supernode/server/api/utils.go
  supernode/server/api/utils_test.go
  supernode/server/handler.go
  supernode/server/preheat_bridge.go
  supernode/server/router.go
  supernode/server/router_test.go
  supernode/server/server.go
  test/request/request.go
Labels: size/XL

#1375 optimize: release allocated ByteBuffer explicitly
  dfget/core/downloader/p2p_downloader/client_stream_writer_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/client_writer_test.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/piece.go
  dfget/core/downloader/p2p_downloader/piece_test.go
  dfget/core/downloader/p2p_downloader/power_client.go
  dfget/core/downloader/p2p_downloader/power_client_test.go
  pkg/pool/buffer_pool.go
  pkg/pool/buffer_pool_test.go
  pkg/pool/writer_pool.go
  pkg/pool/writer_pool_test.go
Labels: areas/test, kind/bug, size/XL

#1412 fix format
  docs/user_guide/install_server.md
Labels: LGTM, size/XS

#1414 fix : spelling mistake
  cmd/dfdaemon/app/init.go
  docs/user_guide/install_client.md
Labels: size/S

#1426 Fix the bug in unit tests about sync.Pool
  pkg/pool/buffer_pool_test.go
  pkg/pool/writer_pool_test.go
Labels: areas/test, kind/bug, size/S

#1411 bugfix: fix dfget panic when crossWrite is true
  dfget/core/downloader/p2p_downloader/client_stream_writer.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/piece.go
  dfget/core/downloader/p2p_downloader/piece_test.go
Labels: kind/bug, kind/panic, priority/P1, size/L

#1429 bugfix: fix missing error message 'Unable to autodetect advertiser ip…
  cmd/supernode/app/root.go
Labels: kind/bug, size/XS

#1435 bugfix: notify supernode client piece task success under cdn pattern
  dfget/core/downloader/p2p_downloader/client_writer.go
Labels: kind/bug, size/XS

#1443 docs: modify the container id to be run in user guide
  docs/user_guide/install_server.md
Labels: areas/docs, size/XS
