Repository dragonflyoss/Dragonfly, pull requests merged in 2020-04, with the labels that each got.

#1264 add stream mode which do not up dfget progress.
  ROADMAP.md
  cmd/dfdaemon/app/init.go
  cmd/dfdaemon/app/root.go
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
  dfdaemon/downloader/downloader.go
  dfdaemon/downloader/p2p/dfclient.go
  dfdaemon/proxy/proxy.go
  dfdaemon/server.go
  dfdaemon/transport/transport.go
Labels: size/XL

#1259 fix: cdn-source pattern supports range task
  dfget/core/api/download_api.go
  dfget/core/api/download_api_test.go
  pkg/rangeutils/range_util.go
  pkg/rangeutils/range_util_test.go
  supernode/daemon/mgr/cdn/downloader.go
  supernode/daemon/mgr/cdn/manager.go
  supernode/daemon/mgr/pieceerror/md5_not_match.go
  supernode/daemon/mgr/task/manager.go
  supernode/daemon/mgr/task/manager_util.go
  supernode/server/0.3_bridge.go
Labels: kind/bug, size/XL

#1267 test: add unit test case for func WithConsole
  pkg/dflog/log_test.go
Labels: areas/test, size/XS

#1271 test: add unit test case for func GetSuperCID
  supernode/config/config_test.go
Labels: areas/test, size/XS

#1275 add lru queue and mockFileServer
  dfget/core/helper/helper_test.go
  dfget/core/helper/test_helper.go
  pkg/queue/lru_queue.go
  pkg/queue/lru_queue_test.go
Labels: size/XL

#1287 docs: fix typo
  docs/user_guide/install_client.md
Labels: LGTM, areas/docs, areas/typo, size/XS

#1277 update api definition of /peer/heartbeat and /peer/network
  apis/swagger.yml
  apis/types/heart_beat_request.go
Labels: areas/network, size/S

#1290 add seed response in seed pattern.
  dfget/types/register_response.go
  dfget/types/report_piece_request.go
  supernode/server/0.3_bridge.go
Labels: size/S

#1291 test: add unit test case for super_reader.go
  supernode/daemon/mgr/cdn/super_reader_test.go
Labels: areas/test, size/S

#1285 pkg: add bitmap in pkg
  go.mod
  go.sum
  pkg/bitmap/bitmap.go
  pkg/bitmap/bitmap_test.go
  pkg/bitmap/utils.go
Labels: size/XXL

#1286 define the interface of seed
  dfdaemon/seed/manager.go
  dfdaemon/seed/seed.go
  dfdaemon/seed/types.go
Labels: size/XL

#1300 feature: allow dfdaemon to listen port on 0~65535
  dfdaemon/config/config.go
  dfdaemon/config/config_test.go
Labels: kind/feature, size/XS

#1297 add seed downloader
  dfdaemon/seed/downloader.go
  dfdaemon/seed/downloader_test.go
  dfdaemon/seed/utils.go
  dfdaemon/seed/utils_test.go
  pkg/errortypes/errortypes.go
Labels: size/XL

#1302 fix: GCDSlice returns 1 when slice is empty
  dfget/config/supernode_value.go
  pkg/algorithm/algorithm.go
  pkg/algorithm/algorithm_test.go
Labels: kind/bug, size/XS

#1310 enhancement: improve GCDSlice performance
  pkg/algorithm/algorithm.go
Labels: kind/enhancement, size/XS

#1316 typo: fix typo cdnDource to cdnSource
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
  dfget/core/downloader/p2p_downloader/power_client.go
Labels: areas/typo, size/XS

#1308 bugfix: notify p2p downloader to pull next piece after reporting
  dfget/core/downloader/p2p_downloader/client_stream_writer.go
  dfget/core/downloader/p2p_downloader/client_stream_writer_test.go
  dfget/core/downloader/p2p_downloader/client_writer.go
  dfget/core/downloader/p2p_downloader/p2p_downloader.go
Labels: kind/bug, size/M
