Repository dragonflyoss/dragonfly, pull requests merged in 2021-09, with the labels that each got.

#591 feat: oauth2
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  go.mod
  go.sum
  manager/auth/oauth/github.go
  manager/auth/oauth/google.go
  manager/auth/oauth/oauth.go
  manager/database/database.go
  manager/handlers/cdn.go
  manager/handlers/cdn_cluster.go
  manager/handlers/oauth.go
  manager/handlers/scheduler.go
  manager/handlers/scheduler_cluster.go
  manager/handlers/security_group.go
  manager/handlers/settings.go
  manager/handlers/user.go
  manager/manager.go
  manager/middlewares/error.go
  manager/middlewares/jwt.go
  manager/model/models.go
  manager/model/oauth.go
  manager/model/settings.go
  manager/model/user.go
  manager/permission/rbac/rbac.go
  manager/permission/rbac/rbac_test.go
  manager/router/router.go
  manager/service/oauth.go
  manager/service/role.go
  manager/service/service.go
  manager/service/settings.go
  manager/service/user.go
  manager/types/cdn.go
  manager/types/oauth.go
  manager/types/scheduler.go
  manager/types/settings.go
  manager/types/user.go
Labels: kind/feature

#596 feat: change scheduler query params
  manager/model/cdn_cluster.go
  manager/model/scheduler_cluster.go
  manager/service/scheduler_cluster.go
  manager/types/scheduler.go
Labels: kind/feature

#611 If peer reschedule parent reach max times notice client back source
  client/daemon/proxy/proxy_sni.go
  scheduler/core/events.go
  scheduler/core/scheduler/basic/basic_scheduler.go
  scheduler/core/scheduler/scheduler.go
  scheduler/core/service.go
Labels: kind/feature

#621 feat: add piece download timeout
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/daemon.go
  client/daemon/peer/piece_downloader.go
  client/daemon/peer/piece_downloader_test.go
  client/daemon/peer/piece_manager.go
  client/daemon/peer/piece_manager_test.go
  docs/en/config/dfget.yaml
Labels: kind/feature

#622 chore: update changelog
  CHANGELOG.md
  Makefile
Labels: kind/feature

#624 chore: skip workflows
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
Labels: kind/feature

#627 test: change preheat e2e timeout
  test/e2e/manager/preheat.go
Labels: kind/feature

#628 docs: install
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
  docs/en/user-guide/install/README.md
  docs/zh-CN/user-guide/install/README.md
Labels: kind/feature

#631 chore: skip e2e
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
Labels: kind/feature

#635 docs: test guide link
  docs/en/README.md
  docs/zh-CN/README.md
Labels: kind/feature

#636 docs: maintainers
  MAINTAINERS.md
Labels: kind/feature

#638 docs: changelog
  CHANGELOG.md
Labels: kind/feature

#639 chore: compatibility with v2.0.0 test
  .github/workflows/compatibility-e2e.yml
Labels: kind/feature

#645 chore: add lucy-cl maintainer
  MAINTAINERS.md
Labels: kind/feature

#647 chore: update version
  version/version.go
Labels: kind/feature

#648 feat: disable prepared statement
  go.mod
  go.sum
  manager/database/database.go
Labels: kind/feature

#649 chore: update maintainers
  MAINTAINERS.md
Labels: kind/feature

#654 docs: scheduler config
  docs/en/config/scheduler.yaml
Labels: kind/feature

#677 chore: e2e workflows remove goproxy
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
Labels: kind/feature

#676 Add manager metrics and logger
  client/daemon/storage/local_storage.go
  go.mod
  go.sum
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/database/database.go
  manager/database/redis_logger.go
  manager/manager.go
  manager/metric/metric.go
  manager/proxy/proxy.go
  manager/router/router.go
  manager/service/service_grpc.go
  pkg/rpc/manager/client/client.go
  pkg/rpc/manager/manager_grpc.pb.go
  pkg/rpc/manager/server/server.go
Labels: kind/feature

#690 chore: update skip-duplicate-actions version
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
Labels: kind/feature

#694 feat: add manager client list scheduler interface
  pkg/rpc/manager/client/client.go
  scheduler/config/mocks/manager_client_mock.go
Labels: kind/feature, manager

#697 chore: workflows ignore paths
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
Labels: kind/feature

#698 docs: scheduler config
  docs/en/config/manager.yaml
  docs/en/config/scheduler.yaml
  docs/zh-CN/config/manager.yaml
  docs/zh-CN/config/scheduler.yaml
Labels: documentation, kind/feature
