Repository dragonflyoss/dragonfly, pull requests merged in 2021-12, with the labels that each got.

#843 feat: add plugin log
  internal/dflog/logger.go
  manager/searcher/searcher.go
  manager/service/service_grpc.go
Labels: kind/feature, manager

#844 feat: searcher plugin change return params
  manager/searcher/searcher.go
  manager/searcher/searcher_test.go
  manager/searcher/testdata/main.go
  manager/searcher/testdata/plugin/searcher.go
  manager/service/service_grpc.go
Labels: kind/feature, manager

#848 feat: get scheduler list with advertise ip
  client/config/dynconfig.go
Labels: kind/feature, dfdaemon

#852 feat: optimize log
  cdn/cdn.go
  cdn/rpcserver/rpcserver.go
  cdn/supervisor/cdn/cache_detector.go
  cdn/supervisor/cdn/downloader.go
  cdn/supervisor/cdn/manager.go
  cdn/supervisor/cdn/storage/storage_gc.go
  cdn/supervisor/progress/manager.go
  cdn/supervisor/task/manager.go
  cdn/supervisor/task/manager_util.go
  manager/manager.go
  manager/service/service_grpc.go
  scheduler/core/events.go
  scheduler/core/service.go
  scheduler/rpcserver/rpcserver.go
  scheduler/scheduler.go
Labels: kind/feature

#856 feat: add scopes validation
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  docs/en/api-reference/api-reference.md
  docs/zh-CN/api-reference/api-reference.md
  manager/types/scheduler_cluster.go
Labels: kind/feature, manager

#857 feat: remove oauth interface auth
  manager/router/router.go
Labels: kind/feature, manager

#863 fix: error log
  pkg/rpc/manager/client/client.go
Labels: kind/feature, manager

#862 feat: move dfnet to internal
  cdn/supervisor/task/manager_util.go
  client/config/flags.go
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/daemon/daemon.go
  client/daemon/daemon_test.go
  client/daemon/peer/peertask_dummy.go
  client/daemon/peer/peertask_file_test.go
  client/daemon/peer/peertask_manager_test.go
  client/daemon/peer/peertask_stream_backsource_partial_test.go
  client/daemon/peer/peertask_stream_test.go
  client/daemon/peer/piece_manager.go
  client/daemon/rpcserver/rpcserver_test.go
  client/daemon/test/mock/scheduler/scheduler_client.go
  cmd/dependency/dependency.go
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  internal/dfnet/dfnet.go
  internal/util/util.go
  internal/util/util_test.go
  pkg/rpc/cdnsystem/client/client.go
  pkg/rpc/client.go
  pkg/rpc/dfdaemon/client/client.go
  pkg/rpc/dfdaemon/client/peer.go
  pkg/rpc/manager/client/client.go
  pkg/rpc/scheduler/client/client.go
  pkg/rpc/server_listen.go
  scheduler/supervisor/cdn.go
  scheduler/supervisor/mocks/cdn_mock.go
Labels: kind/feature

#868 docs: keep alive
  client/daemon/peer/piece_manager.go
  docs/en/deployment/configuration/dfget.yaml
Labels: documentation

#876 feat: add lint makefile
  .github/workflows/lint.yml
  .markdownlint.yml
  Makefile
  hack/markdownlint.sh
Labels: kind/feature

#878 fix: searcher log
  client/daemon/daemon.go
  manager/service/service_grpc.go
Labels: kind/feature

#891 fix: scheduler success event
  scheduler/core/events.go
Labels: kind/feature

#879 refactor: dfpath pkg
  cdn/config/config.go
  client/config/dfget.go
  client/config/dynconfig.go
  client/config/dynconfig_test.go
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/daemon.go
  cmd/cdn/cmd/root.go
  cmd/dependency/plugin_cmd.go
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
  go.sum
  internal/dflog/logcore/init.go
  internal/dfpath/cache_darwin.go
  internal/dfpath/config_darwin.go
  internal/dfpath/config_linux.go
  internal/dfpath/dfpath.go
  internal/dfpath/dfpath_darwin.go
  internal/dfpath/dfpath_linux.go
  internal/dfpath/dfpath_test.go
  internal/dfpath/home_linux.go
  internal/dfpath/log_darwin.go
  internal/dfpath/log_linux.go
  internal/dfplugin/dfplugin.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/manager.go
  manager/router/router.go
  manager/searcher/plugin.go
  manager/searcher/searcher.go
  manager/searcher/searcher_test.go
  manager/searcher/testdata/main.go
  pkg/log/log.go
  pkg/source/plugin.go
  pkg/source/source_client.go
  pkg/source/testdata/main.go
  scheduler/config/config.go
  scheduler/config/config_test.go
  scheduler/config/dynconfig.go
  scheduler/config/dynconfig_test.go
  scheduler/config/testdata/scheduler.yaml
  scheduler/core/evaluator/evaluator.go
  scheduler/core/evaluator/evaluator_test.go
  scheduler/core/evaluator/plugin.go
  scheduler/core/evaluator/testdata/main.go
  scheduler/core/scheduler/basic/basic_scheduler.go
  scheduler/core/scheduler/scheduler.go
  scheduler/core/service.go
  scheduler/scheduler.go
Labels: kind/feature

#895 feat: dfdaemon update content length
  client/daemon/peer/peertask_base.go
Labels: kind/feature

#901 fix: dfget dfpath
  cmd/dfget/cmd/root.go
Labels: kind/feature, dfdaemon

#904 docs: dir path
  docs/en/deployment/configuration/cdn.yaml
  docs/en/deployment/configuration/dfget.yaml
  docs/en/deployment/configuration/scheduler.yaml
  test/testdata/k8s/proxy.yaml
Labels: documentation, kind/feature

#907 feat: add data storage directory
  client/daemon/daemon.go
Labels: kind/feature, dfdaemon

#910 feat: data directory
  client/config/dfget.go
  client/config/peerhost.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  docs/en/deployment/configuration/dfget.yaml
  docs/zh-CN/deployment/configuration/cdn.yaml
  docs/zh-CN/deployment/configuration/dfget.yaml
  docs/zh-CN/deployment/configuration/scheduler.yaml
  internal/dfpath/dfpath.go
  internal/dfpath/dfpath_darwin.go
  internal/dfpath/dfpath_linux.go
  internal/dfpath/dfpath_test.go
Labels: kind/feature, dfdaemon

#911 fix: typo
  docs/en/deployment/configuration/dfget.yaml
Labels: documentation, kind/feature

#913 test: idgen peer id
  internal/idgen/peer_id_test.go
Labels: kind/feature

#909 Update task access time
  cdn/supervisor/progress/manager.go
Labels: kind/bug, cdn

#924 refactor: scheduler register task
  internal/idgen/task_id.go
  pkg/util/net/urlutils/url_utils.go
  scheduler/core/service.go
  scheduler/rpcserver/rpcserver.go
  scheduler/supervisor/task.go
Labels: kind/feature, scheduler

#929 feat: make dfpath package public
  client/daemon/daemon.go
  cmd/cdn/cmd/root.go
  cmd/dependency/dependency.go
  cmd/dependency/plugin_cmd.go
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
  manager/manager.go
  pkg/dfpath/dfpath.go
  pkg/dfpath/dfpath_darwin.go
  pkg/dfpath/dfpath_linux.go
  pkg/dfpath/dfpath_test.go
  pkg/log/log.go
  scheduler/scheduler.go
Labels: kind/feature

#931 feat: make idgen package public
  cdn/rpcserver/rpcserver.go
  cdn/supervisor/cdn/manager_test.go
  client/daemon/daemon.go
  client/daemon/peer/peertask_file.go
  client/daemon/peer/peertask_reuse.go
  client/daemon/peer/peertask_stream.go
  client/daemon/rpcserver/rpcserver.go
  client/daemon/rpcserver/rpcserver_test.go
  client/daemon/transport/transport.go
  client/dfget/dfget_test.go
  pkg/idgen/host_id.go
  pkg/idgen/host_id_test.go
  pkg/idgen/peer_id.go
  pkg/idgen/peer_id_test.go
  pkg/idgen/task_id.go
  pkg/idgen/task_id_test.go
  pkg/idgen/uuid.go
  pkg/idgen/uuid_test.go
  pkg/rpc/dfdaemon/client/client.go
  pkg/rpc/scheduler/client/client.go
  scheduler/core/evaluator/evaluator_base_test.go
  scheduler/job/job.go
  scheduler/rpcserver/rpcserver.go
  scheduler/supervisor/cdn.go
  test/e2e/manager/preheat.go
Labels: kind/feature

#934 feat: add kmutex and krwmutex
  pkg/sync/kmutex.go
  pkg/sync/kmutex_test.go
  pkg/sync/krwmutex.go
  pkg/sync/krwmutex_test.go
  scheduler/core/service.go
Labels: kind/feature, scheduler

#941 fix: size scope empty
  pkg/rpc/scheduler/server/server.go
Labels: kind/feature, scheduler

#946 feat: remove stat log from scheduler
  internal/dflog/logcore/init.go
  internal/dflog/logcore/logcore.go
  internal/dflog/logger.go
  pkg/rpc/scheduler/server/server.go
Labels: kind/feature, scheduler

#964 feat: change metrics service port to 8000
  cdn/config/old_config.go
  cdn/metrics/config.go
Labels: kind/feature, cdn
