Repository dragonflyoss/dragonfly, pull requests merged in 2021-06, with the labels that each got.

#277 Add release workflow and optimize other workflows
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
Labels: kind/feature

#281 Fix CI badge
  README.md
Labels: kind/bug

#272 Add go-cache as local cache, add redis as distributed
  go.mod
  go.sum
  manager/config/config.go
  manager/configsvc/service.go
  manager/dc/redis.go
  manager/lease/id.go
  manager/lease/lease.go
  manager/server/lease_test.go
  manager/server/server.go
  manager/server/server_test.go
  manager/server/service/manager_server.go
  manager/store/orm/cdn_instance.go
  manager/store/orm/lease.go
  manager/store/orm/orm_store.go
  manager/store/orm/scheduler_instance.go
  manager/store/store.go
Labels: kind/feature

#287 Fix hack packaging
  docs/en/config/dfget.yaml
  go.sum
  hack/packaging/config/dfget.yaml
  hack/packaging/deb/build.sh
  hack/packaging/deb/rules
  hack/packaging/rpm/Dockerfile
  hack/packaging/rpm/dfget.spec
  hack/packaging/systemd/dfget-daemon.service
Labels: kind/feature

#283 Refactor mysql table schema, orm json tag.
  go.mod
  go.sum
  manager/apis/v2/handler/scheduler_cluster.go
  manager/apis/v2/types/schema.go
  manager/server/server_test.go
  manager/server/service/manager_server.go
  manager/store/orm/cdn_cluster.go
  manager/store/orm/cdn_instance.go
  manager/store/orm/orm_store.go
  manager/store/orm/scheduler_cluster.go
  manager/store/orm/scheduler_instance.go
  manager/store/orm/security_domain.go
Labels: kind/feature

#295 small PR for code optimization. (#294)
  client/dfget/dfget.go
Labels: kind/feature

#300 Add nfpm build dfget
  Makefile
  build/package/nfpm/config/dfget.yaml
  build/package/nfpm/dfget-postinstall.sh
  build/package/nfpm/dfget-postremove.sh
  build/package/nfpm/dfget-preremove.sh
  build/package/nfpm/dfget.yaml
  build/package/nfpm/systemd/dfget-daemon.service
  build/package/nfpm/systemd/dfget-daemon.service.d/CPUQuota.conf
  build/package/nfpm/systemd/dfget-daemon.service.d/CPUShares.conf
  build/package/nfpm/systemd/dfget-daemon.service.d/MemoryLimit.conf
  build/package/nfpm/systemd/fix.dfget-daemon.cpuset.sh
  hack/packaging/deb/Dockerfile
  hack/packaging/deb/build.sh
  hack/packaging/deb/compat
  hack/packaging/deb/control
  hack/packaging/deb/copyright
  hack/packaging/deb/dfget.manpages
  hack/packaging/deb/dfget.postinst
  hack/packaging/deb/rules
  hack/packaging/rpm/Dockerfile
  hack/packaging/rpm/dfget.spec
  hack/packaging/systemd/dfget-daemon.service.d/CPUQuota.conf
  hack/packaging/systemd/dfget-daemon.service.d/CPUShares.conf
  hack/packaging/systemd/dfget-daemon.service.d/MemoryLimit.conf
Labels: kind/feature

#304 Dynconfig in schduler gets the cdn configuration from the directory
  internal/dynconfig/dynconfig.go
  scheduler/config/config.go
  scheduler/config/config_darwin.go
  scheduler/config/config_linux.go
  scheduler/config/config_test.go
  scheduler/config/dynconfig.go
  scheduler/config/dynconfig_test.go
  scheduler/config/testdata/cdn/cdn_1.json
  scheduler/config/testdata/cdn/cdn_2.json
  scheduler/config/testdata/scheduler.yaml
  scheduler/server/server.go
Labels: kind/feature

#313 Add goreleaser NFPM
  .goreleaser.yml
  Makefile
  build/package/nfpm/dfget.yaml
  docs/ChangeLog
Labels: kind/feature

#317 Fix manager api to config from scheduler_config in swagger yaml
  api/v2/manager/docs.go
  api/v2/manager/swagger.json
  api/v2/manager/swagger.yaml
Labels: bug

#293 Add sqlite, miniredis as mysql, redis mock suite, to f…
  Makefile
  docs/en/config/manager.yaml
  go.mod
  go.sum
  manager/config/config.go
  manager/configsvc/service.go
  manager/server/lease_test.go
  manager/server/mocks/config_mock.go
  manager/server/server.go
  manager/server/server_test.go
  manager/store/client/client.go
  manager/store/orm/orm_store.go
Labels: kind/feature

#319 refactor: update arch
  docs/en/images/arch.png
Labels: kind/feature

#323 Add docker building workflow
  .github/workflows/docker.yml
Labels: kind/feature

#321 Optimize build script
  hack/build.sh
Labels: kind/feature

#325 Improve CONTRIBUTING.md and makefile
  CONTRIBUTING.md
  Makefile
Labels: kind/feature

#326 Update changelog
  CHANGELOG.md
Labels: kind/feature

#328 Increase CI timeout
  .github/workflows/ci.yml
Labels: kind/feature

#341 chore: remove protoc.sh
  hack/protoc.sh
Labels: kind/feature

#342 CDN cache write and detect
  cdnsystem/daemon/cdn/cache_data_mgr.go
  cdnsystem/daemon/cdn/cache_detector.go
  cdnsystem/daemon/cdn/cache_detector_test.go
  cdnsystem/daemon/cdn/cache_detector_util.go
  cdnsystem/daemon/cdn/cache_writer.go
  cdnsystem/daemon/cdn/cache_writer_test.go
  cdnsystem/daemon/cdn/cache_writer_util.go
  cdnsystem/daemon/cdn/cdn_util.go
  cdnsystem/daemon/cdn/manager.go
  cdnsystem/daemon/cdn/manager_test.go
  cdnsystem/daemon/cdn/reporter.go
  cdnsystem/daemon/cdn/storage/disk/disk.go
  cdnsystem/daemon/cdn/storage/hybrid/hybrid.go
  cdnsystem/daemon/cdn/storage/mock/mock_storage_mgr.go
  cdnsystem/daemon/cdn/storage/storage_mgr.go
  cdnsystem/daemon/mock/mock_progress_mgr.go
  cdnsystem/daemon/progress/manager.go
  cdnsystem/daemon/progress/manager_util.go
  cdnsystem/daemon/progress_mgr.go
  cdnsystem/daemon/task/manager_test.go
  cdnsystem/storedriver/local/local_driver_test.go
  cdnsystem/testdata/cdn/download/dra/dragonfly
  cdnsystem/testdata/cdn/download/dra/test1.piece
  cdnsystem/testdata/cdn/download/dra/test2.piece
  cdnsystem/testdata/cdn/go.html
  cdnsystem/testdata/config/cdn.yaml
  cdnsystem/types/seed_task_info.go
  go.mod
  go.sum
  pkg/rpc/examples/cdnsystem/client/main.go
  pkg/util/rangeutils/range.go
Labels: kind/feature

#355 Correct CDN UUID in scheduler
  scheduler/manager/cdn_manager.go
Labels: kind/bug

#361 Modify source client operations
  cdnsystem/daemon/cdn/downloader.go
  cdnsystem/daemon/cdn/manager.go
  cdnsystem/daemon/cdn/manager_test.go
  cdnsystem/daemon/cdn/storage/mock/mock_storage_mgr.go
  cdnsystem/daemon/cdn/storage/storage_mgr.go
  cdnsystem/daemon/cdn_mgr.go
  cdnsystem/daemon/mock/mock_cdn_mgr.go
  cdnsystem/daemon/mock/mock_progress_mgr.go
  cdnsystem/daemon/mock/mock_task_mgr.go
  cdnsystem/daemon/progress_mgr.go
  cdnsystem/daemon/task_mgr.go
  client/daemon/peer/peertask_file_test.go
  client/daemon/peer/peertask_stream_test.go
  internal/rpc/examples/cdnsystem/client/main.go
  pkg/source/hdfsprotocol/hdfs_source_client.go
  pkg/source/headers.go
  pkg/source/httpprotocol/http_source_client.go
  pkg/source/httpprotocol/http_source_client_test.go
  pkg/source/mock/mock_source_client.go
  pkg/source/ossprotocol/oss_source_client.go
  pkg/source/source_client.go
Labels: kind/feature

#368 Add design document
  docs/zh-CN/.gitkeep
  docs/zh-CN/design/architecture.md
  docs/zh-CN/images/arch.png
  docs/zh-CN/images/association.png
  docs/zh-CN/images/download-process.png
  docs/zh-CN/images/logo/dragonfly-linear.png
  docs/zh-CN/images/logo/dragonfly-linear.svg
  docs/zh-CN/images/logo/dragonfly-vertical.png
  docs/zh-CN/images/logo/dragonfly.svg
  docs/zh-CN/images/relation.png
Labels: kind/feature

#373 Feature/dfget param
  client/daemon/service/manager.go
  client/daemon/service/manager_test.go
  client/dfget/dfget.go
  docs/en/images/arch.png
  go.mod
  go.sum
  hack/protoc.sh
  internal/rpc/base/base.pb.go
  internal/rpc/base/base.proto
  internal/rpc/cdnsystem/cdnsystem.pb.go
  internal/rpc/cdnsystem/cdnsystem_grpc.pb.go
  internal/rpc/dfdaemon/client/client.go
  internal/rpc/dfdaemon/dfdaemon.pb.go
  internal/rpc/dfdaemon/dfdaemon.proto
  internal/rpc/dfdaemon/dfdaemon_grpc.pb.go
  internal/rpc/manager/manager.pb.go
  internal/rpc/manager/manager_grpc.pb.go
  internal/rpc/scheduler/scheduler.pb.go
  internal/rpc/scheduler/scheduler_grpc.pb.go
Labels: kind/feature

#382 Repair wrong piece info
  cdnsystem/daemon/cdn/cache_detector.go
  cdnsystem/daemon/cdn/cache_detector_test.go
  cdnsystem/daemon/cdn/cache_writer.go
  cdnsystem/daemon/task/manager_util.go
  cdnsystem/errors/errors.go
  cdnsystem/errors/errors_test.go
  cdnsystem/storedriver/local/local_driver.go
  pkg/source/httpprotocol/http_source_client.go
  pkg/source/ossprotocol/oss_source_client.go
Labels: kind/feature

#388 Add dfget man page
  FAQ.md
  Makefile
  ROADMAP.md
  docs/en/FAQ.md
  docs/en/README.md
  docs/en/ROADMAP.md
  docs/en/cli-reference/dfget.1
  docs/en/cli-reference/dfget.1.md
  docs/en/user-guide/proxy/docker.md
Labels: documentation
