Repository dragonflyoss/dragonfly, pull requests merged in 2021-05, with the labels that each got.

#207 Fix config test
  client/config/peerhost.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.json
  client/config/testdata/config/daemon.yaml
  client/daemon/proxy/proxy.go
  client/daemon/transport/transport.go
  client/daemon/transport/transport_test.go
  go.mod
  go.sum
Labels: kind/bug, kind/feature

#211 Refactor idgen pkg
  pkg/dynconfig/dynconfig_test.go
  pkg/idgen/task_id.go
  pkg/idgen/task_id_test.go
  pkg/util/digestutils/digest.go
  scheduler/scheduler/evaluator_factory.go
  scheduler/service/service.go
Labels: kind/feature

#216 feature: remove redundant configurations
  cdnsystem/config/cdn.yaml
  cdnsystem/config/config.go
  cdnsystem/config/constants.go
  pkg/rpc/scheduler/client/client.go
  scheduler/config/config.go
Labels: kind/feature

#219 Refactor task manager
  scheduler/manager/cdn_manager.go
  scheduler/manager/task_manager.go
  scheduler/manager/task_manager_test.go
  scheduler/server/scheduler_server.go
  scheduler/service/service.go
Labels: kind/feature

#221 Workflows remove main-rc branch
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
Labels: kind/feature

#224 Fix config file nil error
  cmd/common/common.go
Labels: kind/bug

#231 Fix deadlock of CDN GC storage
  cdnsystem/daemon/mgr/task/manager.go
Labels: kind/bug

#230 Refactor CDN subsystem imports more formatter.
  cdnsystem/cdnerrors/errors_test.go
  cdnsystem/cdnutil/cdn_util.go
  cdnsystem/daemon/mgr/cdn/cache_data_mgr.go
  cdnsystem/daemon/mgr/cdn/cache_detector.go
  cdnsystem/daemon/mgr/cdn/cache_detector_util.go
  cdnsystem/daemon/mgr/cdn/cache_writer.go
  cdnsystem/daemon/mgr/cdn/cache_writer_test.go
  cdnsystem/daemon/mgr/cdn/cache_writer_util.go
  cdnsystem/daemon/mgr/cdn/downloader.go
  cdnsystem/daemon/mgr/cdn/manager.go
  cdnsystem/daemon/mgr/cdn/reporter.go
  cdnsystem/daemon/mgr/cdn/storage/hybrid/shm_switch.go
  cdnsystem/daemon/mgr/cdn/storage/path_util.go
  cdnsystem/daemon/mgr/cdn_mgr.go
  cdnsystem/daemon/mgr/progress/manager.go
  cdnsystem/daemon/mgr/progress/manager_util.go
  cdnsystem/daemon/mgr/progress_mgr.go
  cdnsystem/daemon/mgr/task/manager.go
  cdnsystem/daemon/mgr/task/manager_util.go
  cdnsystem/daemon/mgr/task_mgr.go
  cdnsystem/plugins/plugin_manager.go
  cdnsystem/plugins/plugins.go
  cdnsystem/plugins/plugins_test.go
  cdnsystem/server/server.go
  cdnsystem/server/service/cdn_seed_server.go
  cdnsystem/source/ossprotocol/oss_source_client.go
  cdnsystem/source/source_client_util.go
  cdnsystem/storedriver/store.go
  cdnsystem/storedriver/store_mgr.go
  cdnsystem/storedriver/store_mgr_test.go
Labels: kind/feature

#236 refactor: support multi digest not only md5
  cdnsystem/server/service/cdn_seed_server.go
  client/daemon/peer/piece_manager.go
  client/daemon/peer/piece_manager_test.go
  client/daemon/transport/transport.go
  client/dfget/dfget.go
  pkg/idgen/task_id.go
  pkg/rpc/base/base.pb.go
  pkg/rpc/base/base.proto
  pkg/rpc/manager/manager.pb.go
  pkg/rpc/manager/manager_grpc.pb.go
  pkg/rpc/scheduler/scheduler.pb.go
Labels: kind/feature

#243 Fix idgen test
  pkg/idgen/task_id_test.go
Labels: kind/feature

#252 Fix scheduler test
  pkg/cache/cache.go
Labels: kind/feature

#261 Remove pidfile
  client/config/dfget.go
  client/config/dfget_darwin.go
  client/config/dfget_linux.go
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  pkg/pidfile/pidfile.go
Labels: kind/feature

#263 Remove unused public libraries
  pkg/slidingwindow/slidingwindow.go
  pkg/slidingwindow/slidingwindow_test.go
  pkg/util/assertutils/asserts.go
  pkg/util/assertutils/asserts_test.go
Labels: kind/feature

#265 Fix CI badge
  README.md
Labels: kind/feature

#269 Feature/base options
  client/config/peerhost.go
  cmd/cdn/cmd/root.go
  cmd/dependency/base/option.go
  cmd/dependency/dependency.go
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
Labels: kind/bug

#275 Remove custom queue package
  pkg/structure/queue/lru_queue.go
  pkg/structure/queue/lru_queue_test.go
  pkg/structure/queue/queue.go
  pkg/structure/queue/queue_test.go
Labels: kind/feature

#267 Added GC public library
  internal/dynconfig/dynconfig.go
  pkg/gc/gc.go
  pkg/gc/gc_test.go
  pkg/gc/logger.go
  pkg/gc/mocks/logger_mock.go
  pkg/gc/mocks/task_mock.go
  pkg/gc/task.go
Labels: kind/feature
