Repository dragonflyoss/dragonfly, pull requests merged in 2022-06, with the labels that each got.

#1359 docs: update readme system features
  README.md
Labels: documentation, kind/feature

#1363 feat: remove preheat tag required validation
  internal/job/types.go
  manager/job/preheat.go
Labels: kind/feature

#1364 chore: add check size workflows
  .github/workflows/check-size.yml
Labels: kind/feature

#1366 feat: add objectstorage pkg
  go.mod
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/manager.go
  manager/metrics/metrics.go
  pkg/objectstorage/constants.go
  pkg/objectstorage/mocks/objectstorage_mock.go
  pkg/objectstorage/objectstorage.go
  pkg/objectstorage/oss.go
  pkg/objectstorage/s3.go
  scheduler/config/config.go
Labels: kind/feature

#1369 feat: dynconfig add object storage
  client/config/dynconfig.go
  client/config/dynconfig_test.go
  client/config/mocks/manager_client_mock.go
  manager/cache/cache.go
  manager/database/database.go
  manager/database/mysql.go
  manager/manager.go
  manager/router/router.go
  manager/rpcserver/rpcserver.go
  manager/service/bucket.go
  manager/service/service.go
  manager/types/config.go
  pkg/objectstorage/mocks/objectstorage_mock.go
  pkg/rpc/manager/client/client.go
  pkg/rpc/manager/client/mocks/client_mock.go
  pkg/rpc/manager/manager.pb.go
  pkg/rpc/manager/manager.pb.validate.go
  pkg/rpc/manager/manager.proto
Labels: kind/feature, manager, dfdaemon

#1375 fix: preheat tack id
  client/daemon/proxy/proxy.go
  client/daemon/rpcserver/seeder.go
  hack/gen-containerd-hosts.sh
  manager/job/preheat.go
  test/e2e/manager/constants.go
  test/e2e/manager/preheat.go
  test/testdata/containerd/config.toml
Labels: kind/feature, manager, dfdaemon

#1378 feat: remove connection gc
  pkg/rpc/client_util.go
Labels: kind/feature

#1379 feat: dfdaemon add ns filter
  build/package/nfpm/config/dfget.yaml
  deploy/docker-compose/template/dfget.template.yaml
  test/testdata/charts/config.yaml
  test/testdata/k8s/proxy.yaml
Labels: kind/feature

#1382 feat: add EnablePeerGauge config to manager
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/manager.go
  manager/rpcserver/rpcserver.go
Labels: kind/feature, manager

#1385 fix: manager router middlewares order
  manager/middlewares/jwt.go
  manager/router/router.go
Labels: kind/feature, manager

#1376 fix: count error & totalPage error (#1373)
  manager/handlers/handlers.go
  manager/service/application.go
  manager/service/config.go
  manager/service/job.go
  manager/service/oauth.go
  manager/service/scheduler.go
  manager/service/scheduler_cluster.go
  manager/service/security_group.go
  manager/service/security_rule.go
  manager/service/seed_peer.go
  manager/service/seed_peer_cluster.go
  manager/service/user.go
Labels: kind/bug, manager

#1390 feat: dfdaemon add object storage rest api
  .golangci.yml
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/daemon.go
  client/daemon/objectstorage/objectstorage.go
  client/daemon/objectstorage/types.go
  go.mod
  go.sum
  manager/router/router.go
Labels: kind/feature, dfdaemon

#1393 feat: add seed peer for list scheduler grpc interface
  manager/rpcserver/rpcserver.go
Labels: kind/feature, manager

#1398 feat: dfdaemon add GetObject rest api
  client/daemon/daemon.go
  client/daemon/objectstorage/objectstorage.go
  pkg/objectstorage/constants.go
  pkg/objectstorage/objectstorage.go
  pkg/objectstorage/oss.go
  pkg/objectstorage/s3.go
Labels: kind/feature, dfdaemon

#1399 feat: redirect stdout and stderr to file
  cmd/dfget/cmd/daemon.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
  internal/dflog/logger.go
Labels: kind/feature, scheduler, manager

#1403 refactor: digest package
  client/daemon/peer/piece_downloader.go
  client/daemon/peer/piece_manager.go
  client/daemon/storage/local_storage.go
  client/daemon/storage/local_storage_subtask.go
  client/dfget/dfget.go
  client/dfget/dfget_test.go
  go.mod
  go.sum
  pkg/digest/digest.go
  pkg/digest/digest_reader.go
  pkg/digest/digest_reader_test.go
  pkg/digest/digest_test.go
  pkg/digest/mocks/digest_reader_mock.go
Labels: kind/feature

#1404 feat: dfdaemon upload and object storage service add middlewares
  client/daemon/daemon.go
  client/daemon/objectstorage/objectstorage.go
  client/daemon/upload/upload_manager.go
  client/daemon/upload/upload_manager_test.go
Labels: enhancement, kind/feature

#1407 refactor: scheduler announce task
  client/config/peerhost.go
  client/daemon/daemon.go
  client/daemon/peer/peertask_manager.go
  client/daemon/peer/peertask_manager_mock_test.go
  client/daemon/peer/peertask_stream.go
  client/daemon/peer/piece_manager.go
  client/daemon/proxy/proxy.go
  client/daemon/proxy/proxy_manager.go
  client/daemon/rpcserver/rpcserver.go
  client/daemon/test/mock/peer/peertask_manager.go
  client/daemon/transport/transport.go
  client/dfcache/dfcache.go
  pkg/rpc/base/base.pb.go
  pkg/rpc/base/base.proto
  pkg/rpc/dfdaemon/client/client.go
  pkg/rpc/dfdaemon/client/mocks/client_mock.go
  pkg/rpc/dfdaemon/dfdaemon.pb.go
  pkg/rpc/dfdaemon/dfdaemon.pb.validate.go
  pkg/rpc/dfdaemon/dfdaemon.proto
  pkg/rpc/dfdaemon/mocks/dfdaemon_mock.go
  pkg/rpc/manager/mocks/manager_mock.go
  pkg/rpc/scheduler/scheduler.pb.go
  pkg/rpc/scheduler/scheduler.pb.validate.go
  pkg/rpc/scheduler/scheduler.proto
  scheduler/resource/host_manager_test.go
  scheduler/resource/host_test.go
  scheduler/resource/peer_manager_test.go
  scheduler/resource/peer_test.go
  scheduler/resource/seed_peer_test.go
  scheduler/resource/task.go
  scheduler/resource/task_manager_test.go
  scheduler/resource/task_test.go
  scheduler/scheduler/evaluator/evaluator_base_test.go
  scheduler/scheduler/scheduler_test.go
  scheduler/service/service.go
  scheduler/service/service_test.go
Labels: kind/feature, scheduler, dfdaemon

#1408 feat: seed peer add object storage port
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  manager/model/seed_peer.go
  manager/rpcserver/rpcserver.go
  manager/service/seed_peer.go
  manager/types/seed_peer.go
  pkg/rpc/manager/client/mocks/client_mock.go
  pkg/rpc/manager/manager.pb.go
  pkg/rpc/manager/manager.pb.validate.go
  pkg/rpc/manager/manager.proto
Labels: kind/feature, manager

#1410 feat: dfdaemon add destroyObject rest api
  client/daemon/objectstorage/objectstorage.go
  client/daemon/objectstorage/types.go
Labels: kind/feature, dfdaemon

#1413 feat: import object to seed peer with max replicas
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/objectstorage/objectstorage.go
  client/daemon/objectstorage/types.go
  pkg/strings/strings.go
  pkg/strings/strings_test.go
Labels: kind/feature, dfdaemon

#1414 refactor: scheduler http response status code
  scheduler/resource/peer.go
  scheduler/resource/peer_test.go
Labels: kind/feature, scheduler

#1416 feat: remove github/pkg/errors package
  client/clientutil/types.go
  client/config/deprecated.go
  client/config/dfcache.go
  client/config/dfget.go
  client/config/dynconfig_test.go
  client/config/flags.go
  client/config/peerhost.go
  client/daemon/daemon.go
  client/daemon/objectstorage/objectstorage.go
  client/daemon/peer/peertask_conductor.go
  client/daemon/peer/peertask_manager.go
  client/daemon/peer/peertask_piecetask_synchronizer.go
  client/daemon/peer/piece_manager.go
  client/daemon/proxy/proxy.go
  client/daemon/proxy/proxy_manager.go
  client/daemon/proxy/proxy_sni.go
  client/daemon/rpcserver/rpcserver.go
  client/daemon/storage/const.go
  client/daemon/storage/storage_manager.go
  client/dfcache/dfcache.go
  client/dfget/dfget.go
  cmd/dependency/dependency.go
  cmd/dependency/doc_cmd.go
  cmd/dfcache/cmd/export.go
  cmd/dfcache/cmd/import.go
  cmd/dfcache/cmd/root.go
  cmd/dfcache/cmd/stat.go
  cmd/dfget/cmd/daemon.go
  cmd/dfget/cmd/root.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
  go.mod
  internal/dferrors/error.go
  internal/job/job.go
  internal/job/queue.go
  manager/middlewares/error.go
  manager/service/user.go
  pkg/dfnet/dfnet.go
  pkg/dfpath/dfpath.go
  pkg/digest/digest_reader.go
  pkg/net/http/range.go
  pkg/net/ip/ip.go
  pkg/objectstorage/oss.go
  pkg/rpc/cdnsystem/client/client.go
  pkg/rpc/cdnsystem/client/piece_seed_stream.go
  pkg/rpc/client.go
  pkg/rpc/dfdaemon/client/client.go
  pkg/rpc/dfdaemon/client/down_result_stream.go
  pkg/rpc/scheduler/client/client.go
  pkg/rpc/vsock.go
  pkg/source/clients/hdfsprotocol/hdfs_source_client.go
  pkg/source/clients/hdfsprotocol/hdfs_source_client_test.go
  pkg/source/clients/httpprotocol/http_source_client_test.go
  pkg/source/clients/ossprotocol/oss_source_client.go
  pkg/source/request.go
  pkg/source/source_client.go
  pkg/unit/byte.go
  scheduler/config/config.go
  scheduler/config/dynconfig_test.go
  scheduler/resource/seed_peer.go
Labels: kind/feature

#1417 feat: update golang to 1.18.3
  .github/workflows/check-size.yml
  .github/workflows/ci.yml
  .github/workflows/compatibility-e2e.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  build/images/base/Dockerfile
  build/images/base/README.md
  build/images/dfdaemon/Dockerfile
  build/images/manager/Dockerfile
  build/images/scheduler/Dockerfile
  build/plugin-builder/Dockerfile
  build/plugin-builder/images/dfdaemon/Dockerfile
  build/plugin-builder/images/manager/Dockerfile
  build/plugin-builder/images/scheduler/Dockerfile
  go.mod
  go.sum
  hack/build.sh
  hack/docker-build.sh
  test/tools/no-content-length/Dockerfile
Labels: kind/feature

#1420 feat: rename client/clientutil to client/util
  client/config/dfget.go
  client/config/dfget_darwin.go
  client/config/dfget_linux.go
  client/config/flags.go
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/daemon/daemon.go
  client/daemon/objectstorage/objectstorage.go
  client/daemon/peer/peertask_conductor.go
  client/daemon/peer/peertask_file.go
  client/daemon/peer/peertask_manager.go
  client/daemon/peer/peertask_manager_test.go
  client/daemon/peer/peertask_reuse.go
  client/daemon/peer/peertask_reuse_test.go
  client/daemon/peer/peertask_seed.go
  client/daemon/peer/peertask_stream.go
  client/daemon/peer/peertask_stream_backsource_partial_test.go
  client/daemon/peer/piece_downloader_test.go
  client/daemon/peer/piece_manager.go
  client/daemon/peer/piece_manager_test.go
  client/daemon/rpcserver/rpcserver.go
  client/daemon/rpcserver/rpcserver_test.go
  client/daemon/rpcserver/seeder.go
  client/daemon/rpcserver/seeder_test.go
  client/daemon/storage/local_storage.go
  client/daemon/storage/local_storage_subtask.go
  client/daemon/storage/local_storage_test.go
  client/daemon/storage/metadata.go
  client/daemon/storage/mocks/stroage_manager_mock.go
  client/daemon/storage/storage_manager.go
  client/daemon/transport/transport.go
  client/daemon/upload/upload_manager.go
  client/util/keepalive.go
  client/util/mocks/keepalive_mock.go
  client/util/range.go
  client/util/range_test.go
  client/util/types.go
  cmd/dependency/dependency.go
  scheduler/resource/peer_test.go
  test/e2e/dfget_test.go
Labels: kind/feature

#1421 feat: GetObjectInput add range field
  client/dfstore/dfstore.go
Labels: kind/feature

#1422 feat: used put object action
  client/daemon/objectstorage/objectstorage.go
  client/daemon/objectstorage/types.go
  client/dfstore/dfstore.go
  client/dfstore/mocks/dfstore_mock.go
  pkg/objectstorage/mocks/objectstorage_mock.go
  pkg/objectstorage/objectstorage.go
  pkg/objectstorage/oss.go
  pkg/objectstorage/s3.go
Labels: kind/feature, dfdaemon

#1424 feat: dfstore closes writer
  client/config/dynconfig.go
  client/config/dynconfig_test.go
  client/config/mocks/dynconfig_mock.go
  client/dfstore/dfstore.go
Labels: kind/feature, dfdaemon
