Repository dragonflyoss/dragonfly, pull requests merged in 2023-01, with the labels that each got.

#1965 chore: change codecov coverage range
  codecov.yml
Labels: kind/feature

#1964 fix: config decode net.IP
  cmd/dependency/dependency.go
Labels: kind/feature, manager

#1967 chore: goreleaser set rlcp field
  .goreleaser.yml
Labels: kind/feature

#1971 fix: context of trigger seed peer
  scheduler/service/service.go
Labels: kind/feature, scheduler

#1977 chore: remove codecov patch feature
  codecov.yml
Labels: kind/feature

#1976 feat: add S3ForcePathStyle to object storage
  client/daemon/objectstorage/objectstorage.go
  codecov.yml
  go.mod
  go.sum
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/manager.go
  manager/rpcserver/rpcserver.go
  pkg/objectstorage/objectstorage.go
  pkg/objectstorage/s3.go
Labels: kind/feature, manager, dfdaemon

#1979 feat: add udp ping to the net package
  go.mod
  go.sum
  pkg/net/ping/ping.go
  pkg/net/ping/ping_test.go
Labels: kind/feature

#1991 feat: searcher can not found candidate scheduler clusters, return all scheduler clusters
  manager/metrics/metrics.go
  manager/rpcserver/rpcserver.go
Labels: kind/feature, manager

#1990 feat: add manager v2 api
  client/config/dynconfig.go
  client/config/dynconfig_manager.go
  client/config/dynconfig_manager_test.go
  client/config/dynconfig_test.go
  client/config/mocks/dynconfig_mock.go
  client/daemon/announcer/announcer.go
  client/daemon/announcer/announcer_test.go
  client/daemon/daemon.go
  client/daemon/peer/peertask_manager_mock.go
  client/daemon/peer/piece_manager_mock.go
  client/daemon/rpcserver/mocks/rpcserver_mock.go
  client/daemon/storage/mocks/stroage_manager_mock.go
  go.mod
  go.sum
  manager/rpcserver/manager_server_v1.go
  manager/rpcserver/manager_server_v2.go
  manager/rpcserver/rpcserver.go
  manager/rpcserver/security_server_v1.go
  manager/rpcserver/security_server_v1_test.go
  manager/searcher/mocks/searcher_mock.go
  manager/searcher/searcher.go
  manager/searcher/searcher_test.go
  manager/searcher/testdata/main.go
  pkg/issuer/dragonfly.go
  pkg/rpc/cdnsystem/client/mocks/client_mock.go
  pkg/rpc/dfdaemon/client/mocks/client_mock.go
  pkg/rpc/manager/client/constants.go
  pkg/rpc/manager/client/mocks/client_mock.go
  pkg/rpc/manager/client/mocks/v1_mock.go
  pkg/rpc/manager/client/mocks/v2_mock.go
  pkg/rpc/manager/client/v1.go
  pkg/rpc/manager/client/v2.go
  pkg/rpc/manager/server/server.go
  pkg/rpc/scheduler/client/mocks/client_mock.go
  pkg/rpc/security/client/mocks/v1_mock.go
  pkg/rpc/security/client/v1.go
  scheduler/announcer/announcer.go
  scheduler/announcer/announcer_test.go
  scheduler/config/dynconfig.go
  scheduler/config/dynconfig_test.go
  scheduler/config/mocks/dynconfig_mock.go
  scheduler/resource/seed_peer_client_mock.go
  scheduler/resource/seed_peer_mock.go
  scheduler/scheduler.go
Labels: kind/feature, manager

#1992 fix: manager grpc filename
  pkg/rpc/manager/client/client_v1.go
  pkg/rpc/manager/client/client_v2.go
  pkg/rpc/manager/client/mocks/client_v1_mock.go
  pkg/rpc/manager/client/mocks/client_v2_mock.go
Labels: kind/feature, manager

#1993 fix: count of total page in pagination
  manager/handlers/handlers.go
Labels: kind/feature, manager

#2007 feat: remove NetTopology from scheduler and manager
  build/package/nfpm/config/dfget.yaml
  client/config/dynconfig_manager.go
  client/config/peerhost.go
  client/config/peerhost_darwin.go
  client/config/peerhost_linux.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/announcer/announcer.go
  client/daemon/daemon.go
  client/daemon/peer/peertask_conductor.go
  client/daemon/peer/peertask_manager.go
  client/daemon/peer/peertask_manager_test.go
  client/daemon/peer/peertask_piecetask_synchronizer.go
  client/daemon/rpcserver/seeder.go
  deploy/docker-compose/template/dfget.template.yaml
  deploy/docker-compose/template/scheduler.template.yaml
  deploy/docker-compose/template/seed-peer.template.yaml
  go.mod
  go.sum
  manager/model/scheduler.go
  manager/model/seed_peer.go
  manager/rpcserver/manager_server_v1.go
  manager/rpcserver/manager_server_v2.go
  manager/searcher/searcher.go
  manager/searcher/searcher_test.go
  manager/service/scheduler.go
  manager/service/seed_peer.go
  manager/types/scheduler.go
  manager/types/scheduler_cluster.go
  manager/types/seed_peer.go
  manager/types/seed_peer_cluster.go
  scheduler/announcer/announcer.go
  scheduler/announcer/announcer_test.go
  scheduler/config/config.go
  scheduler/config/config_test.go
  scheduler/config/dynconfig_test.go
  scheduler/config/testdata/scheduler.yaml
  scheduler/resource/host_test.go
  scheduler/resource/seed_peer_client.go
  scheduler/resource/seed_peer_client_test.go
  scheduler/rpcserver/scheduler_server_v1.go
  scheduler/rpcserver/scheduler_server_v2.go
  scheduler/scheduler/evaluator/evaluator_base.go
  scheduler/scheduler/evaluator/evaluator_base_test.go
  scheduler/scheduler/scheduler_test.go
  scheduler/service/service_v1.go
  scheduler/service/service_v1_test.go
  scheduler/storage/storage_test.go
  scheduler/storage/types.go
Labels: enhancement

#2009 chore: generate manager swagger
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
Labels: kind/feature

#2010 feat: change ok to loaded in loading func
  manager/searcher/searcher_test.go
  scheduler/resource/host.go
  scheduler/resource/host_manager.go
  scheduler/resource/host_manager_test.go
  scheduler/resource/host_test.go
  scheduler/resource/peer_manager.go
  scheduler/resource/peer_manager_test.go
  scheduler/resource/peer_test.go
  scheduler/resource/seed_peer.go
  scheduler/resource/seed_peer_client.go
  scheduler/resource/task.go
  scheduler/resource/task_manager.go
  scheduler/resource/task_manager_test.go
  scheduler/resource/task_test.go
  scheduler/scheduler/scheduler.go
  scheduler/scheduler/scheduler_test.go
  scheduler/service/service_v1.go
  scheduler/service/service_v1_test.go
Labels: kind/feature

#2013 chore: fix workflows typo
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: kind/feature

#2008 feat: support source client option
  client/config/peerhost.go
  client/daemon/daemon.go
  cmd/dfget/cmd/root.go
  cmd/dfget/main.go
  pkg/source/clients/example/dfs.go
  pkg/source/clients/hdfsprotocol/hdfs_source_client.go
  pkg/source/clients/httpprotocol/http_source_client.go
  pkg/source/clients/httpprotocol/http_source_client_test.go
  pkg/source/clients/orasprotocol/oras_source_client.go
  pkg/source/clients/ossprotocol/oss_source_client.go
  pkg/source/clients/s3protocol/s3_source_client.go
  pkg/source/loader/oras.go
  pkg/source/source_client_builder.go
  pkg/source/transport_option.go
Labels: enhancement, dfdaemon

#2012 feat: change peer's piece type in resource
  scheduler/resource/peer.go
  scheduler/resource/piece.go
  scheduler/resource/piece_test.go
  scheduler/resource/seed_peer.go
  scheduler/service/service_v1.go
Labels: kind/feature, scheduler

#1978 refactor: piece_dispatcher considering score of parent peer
  client/config/constants.go
  client/daemon/peer/peertask_conductor.go
  client/daemon/peer/peertask_piecetask_synchronizer.go
  client/daemon/peer/piece_dispatcher.go
  client/daemon/peer/piece_dispatcher_test.go
  client/daemon/peer/piece_downloader.go
  client/daemon/peer/piece_manager.go
Labels: dfdaemon

#2014 feat: add directed graph to pkg
  pkg/graph/dag/dag.go
  pkg/graph/dag/dag_test.go
  pkg/graph/dag/mocks/dag_mock.go
  pkg/graph/dag/vertex.go
  pkg/graph/dag/vertex_test.go
  pkg/graph/dg/dg.go
  pkg/graph/dg/dg_test.go
  pkg/graph/dg/mocks/dg_mock.go
  pkg/graph/dg/vertex.go
  pkg/graph/dg/vertex_test.go
  scheduler/resource/task.go
Labels: kind/feature

#2016 feat: update dingtalk qrcode
  docs/images/community/dingtalk-group.jpeg
Labels: kind/feature

#2017 docs: change introduction in readem
  README.md
Labels: kind/feature
