Repository dragonflyoss/dragonfly, pull requests merged in 2023-08, with the labels that each got.

#2590 feat: add personal access token middleware to open api
  manager/manager.go
  manager/middlewares/personal_access_token.go
  manager/models/personal_access_token.go
  manager/router/router.go
Labels: enhancement, manager

#2591 feat: implement DeleteSeedPeer api in manager
  go.mod
  go.sum
  manager/rpcserver/manager_server_v2.go
  pkg/rpc/manager/client/client_v2.go
  pkg/rpc/manager/client/mocks/client_v2_mock.go
Labels: enhancement

#2592 feat: change seed peer state to active in UpdateSeedPeer api
  manager/rpcserver/manager_server_v1.go
  manager/rpcserver/manager_server_v2.go
Labels: enhancement

#2593 feat: create seed peer with active state in manager
  manager/rpcserver/manager_server_v2.go
Labels: enhancement

#2595 feat: use unscoped delete for resource in manager
  manager/service/application.go
  manager/service/cluster.go
  manager/service/config.go
  manager/service/job.go
  manager/service/oauth.go
  manager/service/personal_access_token.go
  manager/service/scheduler.go
  manager/service/scheduler_cluster.go
  manager/service/seed_peer.go
  manager/service/seed_peer_cluster.go
Labels: enhancement, manager

#2604 feat: change default cluster name to cluster-1
  manager/database/database.go
Labels: enhancement, manager

#2612 feat: add tls client config for preheat in manager
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/job/job.go
  manager/job/preheat.go
Labels: enhancement, manager

#2613 fix: directories created via os.MkdirAll are not checked for permissions
  client/config/dfcache.go
  client/config/dfget.go
  client/config/dfget_test.go
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  client/daemon/peer/peertask_manager_test.go
  client/daemon/peer/peertask_stream_backsource_partial_test.go
  client/daemon/peer/peertask_stream_resume_test.go
  client/daemon/peer/piece_manager_test.go
  client/daemon/peer/traffic_shaper_test.go
  client/daemon/rpcserver/rpcserver.go
  client/daemon/storage/const.go
  cmd/dependency/doc_cmd.go
  internal/dflog/loginit.go
  pkg/cache/cache.go
  pkg/dfpath/dfpath.go
  pkg/dfpath/dfpath_darwin.go
  pkg/dfpath/dfpath_linux.go
  trainer/storage/storage_test.go
Labels: enhancement

#2614 feat: add lock to dag vertex and replace rand.Seed with rand.New
  pkg/graph/dag/dag.go
  pkg/graph/dag/vertex.go
  scheduler/resource/task.go
Labels: enhancement

#2615 fix: manager generates mTLS certificates for arbitrary IP addresses
  manager/rpcserver/security_server_v1.go
  manager/rpcserver/security_server_v1_test.go
Labels: enhancement, manager

#2616 chore: update d7y.io/api version to v2.0.18
  go.mod
  go.sum
Labels: enhancement

#2619 fix: usage of architecture-dependent int type in the scheduler
  scheduler/service/service_v1.go
Labels: enhancement

#2618 fix: incorrect log message in the scheduler
  scheduler/service/service_v1.go
Labels: enhancement, scheduler

#2617 feat: download tiny file with https scheme
  manager/config/config.go
  manager/config/config_test.go
  manager/config/constants.go
  manager/config/testdata/manager.yaml
  manager/job/job.go
  manager/job/preheat.go
  scheduler/config/config.go
  scheduler/config/config_test.go
  scheduler/config/constants.go
  scheduler/config/testdata/scheduler.yaml
  scheduler/resource/host_manager_test.go
  scheduler/resource/host_test.go
  scheduler/resource/peer.go
  scheduler/resource/peer_manager_test.go
  scheduler/resource/peer_test.go
  scheduler/resource/resource.go
  scheduler/resource/seed_peer.go
  scheduler/resource/seed_peer_test.go
  scheduler/resource/task_manager_test.go
  scheduler/resource/task_test.go
  scheduler/scheduling/evaluator/evaluator_base_test.go
  scheduler/scheduling/scheduling_test.go
  scheduler/service/service_v1.go
  scheduler/service/service_v1_test.go
  scheduler/service/service_v2.go
  scheduler/service/service_v2_test.go
Labels: enhancement

#2622 feat: net.JoinHostPort replace fmt.Sprintf
  client/config/dfstore.go
Labels: enhancement

#2623 feat: change cache size in manager
  manager/config/constants.go
Labels: enhancement, manager

#2624 fix: list personal access token with query string
  manager/service/personal_access_token.go
  manager/types/persional_access_token.go
Labels: enhancement, manager

#2632 feat: case insensitive string comparison in evaluater package of the manager
  manager/searcher/searcher.go
  manager/searcher/searcher_test.go
  scheduler/scheduling/evaluator/evaluator_base.go
Labels: enhancement, manager

#2633 feat: change cache size in manager
  manager/config/constants.go
Labels: enhancement

#2643 test: add unit tests for dfstore
  client/config/dfstore_test.go
Labels: enhancement

#2644 test: rename Test_Validate to TestDfstoreConfig_Validate
  client/config/dfstore_test.go
Labels: enhancement

#2653 feat: change max PerPage to 10000000
  manager/types/application.go
  manager/types/cluster.go
  manager/types/config.go
  manager/types/job.go
  manager/types/model.go
  manager/types/oauth.go
  manager/types/persional_access_token.go
  manager/types/scheduler.go
  manager/types/scheduler_cluster.go
  manager/types/seed_peer.go
  manager/types/seed_peer_cluster.go
  manager/types/user.go
Labels: enhancement

#2654 feat: peer information is changed from being stored in metrics to being stored in mysql
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  manager/config/config.go
  manager/config/config_test.go
  manager/config/testdata/manager.yaml
  manager/database/database.go
  manager/handlers/peer.go
  manager/metrics/metrics.go
  manager/models/peer.go
  manager/models/scheduler_cluster.go
  manager/router/router.go
  manager/rpcserver/manager_server_v1.go
  manager/rpcserver/manager_server_v2.go
  manager/rpcserver/rpcserver.go
  manager/service/peer.go
  manager/service/service.go
  manager/types/peer.go
Labels: enhancement, manager

#2663 feat: add sync peer job for scheduler
  internal/job/constants.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/constant_otel.go
  manager/config/constants.go
  manager/config/testdata/manager.yaml
  manager/job/job.go
  manager/job/mocks/sync_peers_mock.go
  manager/job/preheat.go
  manager/job/sync_peers.go
  manager/service/mocks/service_mock.go
  scheduler/job/job.go
  scheduler/resource/host_manager.go
  scheduler/resource/host_manager_mock.go
  scheduler/resource/peer_manager.go
  scheduler/resource/peer_manager_mock.go
  scheduler/resource/task_manager.go
  scheduler/resource/task_manager_mock.go
Labels: enhancement, scheduler

#2664 feat: add createSyncPeers to async job in manager
  manager/config/config.go
  manager/job/job.go
  manager/job/preheat.go
  manager/job/sync_peers.go
  manager/manager.go
Labels: enhancement, manager

#2668 feat: merge sync peer with peer table in manager
  client/daemon/announcer/announcer.go
  client/daemon/daemon.go
  go.mod
  go.sum
  internal/dflog/logger.go
  internal/job/job.go
  internal/job/job_test.go
  internal/job/queue_test.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/constants.go
  manager/config/testdata/manager.yaml
  manager/job/mocks/sync_peers_mock.go
  manager/job/sync_peers.go
  manager/manager.go
  pkg/digest/digest_reader_test.go
  scheduler/job/job.go
  scheduler/resource/host.go
  scheduler/resource/host_test.go
  scheduler/service/service_v1.go
  scheduler/service/service_v2.go
Labels: enhancement, manager

#2669 docs: add GOVERNANCE.md to dragonfly project
  GOVERNANCE.md
Labels: documentation, enhancement

#2671 docs: add OWNERS.md to project
  ADOPTERS.md
  MAINTAINERS.md
  OWNERS.md
Labels: documentation

#2672 feat: remove IsPrivate from safeSocketControl
  pkg/net/http/http.go
Labels: enhancement

#2673 docs: add Akash HR to maintainers
  MAINTAINERS.md
Labels: enhancement

#2674 feat: add idc and location to ListSchedulers in manager
  go.mod
  go.sum
  manager/rpcserver/manager_server_v2.go
Labels: enhancement, manager

#2682 feat: initialize object storage client in the New func
  client/daemon/objectstorage/objectstorage.go
Labels: enhancement, client

#2685 chore: update api verison to v2.0.25
  go.mod
  go.sum
Labels: enhancement

#2687 chore: maintainer in alphabetical order of the company
  MAINTAINERS.md
  OWNERS.md
Labels: enhancement

#2686 feat: optimize GetObjectMetadatasInput validate in dfstore
  client/dfstore/dfstore.go
  client/dfstore/mocks/dfstore_mock.go
  pkg/objectstorage/constants.go
  pkg/objectstorage/objectstorage.go
  pkg/objectstorage/obs.go
  pkg/objectstorage/oss.go
  pkg/objectstorage/s3.go
Labels: enhancement

#2688 fix: Vertex.DeleteInEdges and Vertex.DeleteOutEdges functions are not thread safe
  pkg/graph/dag/dag.go
  pkg/graph/dag/dag_test.go
  pkg/graph/dag/mocks/dag_mock.go
  pkg/graph/dag/vertex.go
  pkg/graph/dag/vertex_test.go
  pkg/graph/dg/dg.go
  pkg/graph/dg/dg_test.go
  pkg/graph/dg/mocks/dg_mock.go
  pkg/graph/dg/vertex.go
  pkg/graph/dg/vertex_test.go
  pkg/objectstorage/mocks/objectstorage_mock.go
  scheduler/resource/task.go
Labels: scheduler, bug

#2690 docs: remove china mobile in ADOPTERS.md
  ADOPTERS.md
Labels: enhancement
