Repository dragonflyoss/dragonfly, pull requests merged in 2024-03, with the labels that each got.

#3095 fix: typo in scheduler config
  scheduler/config/config.go
Labels: enhancement

#3097 feat: change scheduling params
  scheduler/config/constants.go
Labels: enhancement, scheduler

#3098 chore: update api version
  go.mod
  go.sum
Labels: enhancement

#3105 fix: erorr middleware set error message return headers were already written
  manager/middlewares/error.go
  manager/router/router.go
Labels: enhancement

#3107 feat: change peer count limit for task
  scheduler/resource/task.go
Labels: enhancement

#3115 chore: add check-size to actions
  .github/workflows/check-size.yml
Labels: enhancement

#3120 chore: remove tips in actions
  .github/workflows/compatibility-e2e.yml
  .github/workflows/docker.yml
  .github/workflows/e2e.yml
Labels: enhancement

#3122 feat: rename e2eutil to util
  test/e2e/concurrency_test.go
  test/e2e/containerd_test.go
  test/e2e/dfget_test.go
  test/e2e/e2e_test.go
  test/e2e/manager/preheat.go
  test/e2e/util/artifact.go
  test/e2e/util/exec.go
  test/e2e/util/feature_gate.go
  test/e2e/util/file_server.go
Labels: enhancement

#3129 chore: update api verison to v2.0.106
  go.mod
  go.sum
Labels: enhancement

#3133 chore: rename test actions
  .github/workflows/compatibility-e2e-with-client-go.yml
  .github/workflows/e2e-with-client-go.yml
  .github/workflows/e2e-with-client-rs.yml
Labels: enhancement

#3142 fix: scheduler storage buffer size limit
  cmd/trainer/cmd/root.go
  scheduler/config/config.go
  scheduler/config/config_test.go
Labels: scheduler

#3152 feat: optimize graph based on sync.Map
  pkg/container/set/safe_set.go
  pkg/container/set/set.go
  pkg/graph/dag/dag.go
  pkg/graph/dag/dag_test.go
  pkg/graph/dag/mocks/dag_mock.go
  pkg/graph/dag/vertex.go
  pkg/graph/dg/dg.go
  pkg/graph/dg/dg_test.go
  pkg/graph/dg/mocks/dg_mock.go
  pkg/graph/dg/vertex.go
  scheduler/resource/task.go
Labels: enhancement, scheduler
