Repository dragonflyoss/dragonfly, pull requests merged in 2025-09, with the labels that each got.

#4327 docs(README): update project description and structure
  README.md
Labels: documentation

#4330 docs: fix maintainer links in MAINTAINERS.md and OWNERS.md
  MAINTAINERS.md
  OWNERS.md
Labels: documentation

#4331 docs: update community links in project documentation
  OWNERS.md
Labels: documentation, cncf-request

#4340 refactor(host_manager): separate normal and seed host maps
  scheduler/resource/standard/host_manager.go
  scheduler/resource/standard/host_manager_mock.go
Labels: enhancement

#4355 refactor(types): remove strong and weak host types
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  client/config/peerhost_test.go
  client/config/testdata/config/daemon.yaml
  manager/types/peer.go
  manager/types/seed_peer.go
  pkg/types/types.go
  scheduler/config/dynconfig_test.go
  scheduler/service/service_v1_test.go
  scheduler/service/service_v2.go
Labels: enhancement
