Repository dragonflyoss/dragonfly, pull requests merged in 2025-05, with the labels that each got.

#4037 comments(auth/oauth): add default timeout comments for oauth
  manager/auth/oauth/oauth.go
Labels: documentation

#4042 refactor: pass context to run gc task
  manager/gc/audit.go
  manager/gc/job.go
  manager/manager.go
  pkg/gc/gc.go
  pkg/gc/gc_mock.go
  pkg/gc/gc_test.go
  pkg/gc/runner_mock.go
  pkg/gc/task.go
  scheduler/resource/persistentcache/host_manager.go
  scheduler/resource/persistentcache/host_manager_mock.go
  scheduler/resource/persistentcache/host_manager_test.go
  scheduler/resource/standard/host_manager.go
  scheduler/resource/standard/host_manager_mock.go
  scheduler/resource/standard/host_manager_test.go
  scheduler/resource/standard/peer_manager.go
  scheduler/resource/standard/peer_manager_mock.go
  scheduler/resource/standard/peer_manager_test.go
  scheduler/resource/standard/task_manager.go
  scheduler/resource/standard/task_manager_mock.go
  scheduler/resource/standard/task_manager_test.go
  scheduler/scheduler.go
Labels: enhancement

#4044 comments(manager/config): add GRPCConfig struct for gRPC server confi…
  manager/config/config.go
Labels: documentation

#4043 feat(manager/config): add RedisConfig with documentation
  manager/config/config.go
Labels: documentation

#4046 Correct error logging format in InitMonitor function
  cmd/dependency/dependency.go
Labels: go, bug

#4041 feat(manager): add redis proxy for manager and support redis username
  go.mod
  go.sum
  internal/job/job.go
  internal/job/job_test.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/constants.go
  manager/config/testdata/manager.yaml
  manager/job/preheat.go
  manager/job/sync_peers.go
  manager/job/task.go
  manager/job/task_test.go
  manager/manager.go
  manager/service/job.go
  manager/service/preheat.go
  pkg/redis/proxy.go
  scheduler/job/job.go
  test/e2e/v1/manager/preheat.go
  test/e2e/v2/manager/job.go
Labels: enhancement

#4048 comments(manager/gc): add NewAuditGCTask function
  manager/gc/audit.go
Labels: documentation

#4052 refactor(manager/handlers/bucket.go): Reorder imports for clarity
  manager/handlers/bucket.go
Labels: documentation

#4061 feat(middlewares): add CreateJobRateLimiter middleware
  manager/middlewares/ratelimiter.go
Labels: documentation

#4062 refactor(manager): redis proxy to use bufio.Reader for protocol detection
  manager/database/database.go
  pkg/redis/proxy.go
  pkg/redis/redis.go
Labels: enhancement, manager

#4066 feat: support preheat by peer count
  internal/job/types.go
  manager/job/preheat.go
  manager/types/job.go
  scheduler/job/job.go
Labels: enhancement, manager

#4064 feat: add the storage pkg for stat task
  pkg/idgen/task_id.go
  pkg/storage/piece.go
  pkg/storage/piece_test.go
  pkg/storage/stat_task.go
  pkg/storage/stat_task_test.go
Labels: enhancement

#4068 feat: implement distributed rate limiting by redis_rate/v10
  go.mod
  go.sum
  internal/ratelimiter/distributed_ratelimiter.go
  internal/ratelimiter/job_ratelimiter.go
  manager/config/constants.go
  manager/middlewares/ratelimiter.go
Labels: enhancement, manager

#4067 fix: add the authorization for get configs API
  manager/router/router.go
Labels: enhancement

#4069 feat(manager): add cleanup of associated tables in job garbage collection
  manager/gc/job.go
Labels: enhancement

#4071 comments(router): add Init function to initialize gin engine
  manager/router/router.go
Labels: documentation

#4072 feat: Update machinery to v1.10.13 and optimize Redis connection pool for weak network conditions
  go.mod
  go.sum
  internal/job/constants.go
  internal/job/job.go
  manager/job/preheat.go
  manager/job/task.go
Labels: enhancement

#4075 feat: update machinery to v1.10.14 and adjust Redis config
  go.mod
  go.sum
  internal/job/constants.go
Labels: enhancement

#4086 feat: update Redis connection pool configuration
  client/daemon/pex/peer_exchange_test.go
  internal/job/constants.go
  manager/cache/cache.go
  manager/config/config.go
  manager/config/config_test.go
  manager/config/constants.go
  manager/config/testdata/manager.yaml
Labels: enhancement

#4088 feat(manager): add ratelimiter for job oapi
  client/daemon/peer/piece_dispatcher_test.go
  codecov.yml
  manager/router/router.go
Labels: enhancement

#4074 feat: add the API for trigger the GC manually
  internal/job/constants.go
  manager/gc/audit.go
  manager/gc/job.go
  manager/gc/recorder.go
  manager/handlers/job.go
  manager/manager.go
  manager/service/job.go
  manager/service/mocks/service_mock.go
  manager/service/service.go
  manager/types/job.go
  pkg/gc/gc.go
Labels: enhancement

#4089 feat: set poolSize and poolTimeout for manager
  internal/job/constants.go
  manager/config/constants.go
  manager/database/database.go
  pkg/redis/redis.go
  scheduler/config/config.go
  scheduler/config/config_test.go
  scheduler/config/constants.go
  scheduler/config/testdata/scheduler.yaml
  scheduler/scheduler.go
Labels: enhancement

#4091 Add Chlins Zhang as maintainer
  MAINTAINERS.md
Labels: documentation

#4093 chore(README.md): add maintainer google groups for communication channels and remove discussion group
  README.md
Labels: documentation

#4092 docs(host.go): Update NewHost comment for clarity
  scheduler/resource/persistentcache/host.go
Labels: documentation
