Repository dragonflyoss/dragonfly, pull requests merged in 2025-04, with the labels that each got.

#3929 feat(manager): optimize service of the persistent cache task
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  manager/handlers/persistent_cache.go
  manager/handlers/persistent_cache_task.go
  manager/handlers/persistent_cache_test.go
  manager/router/router.go
  manager/service/mocks/service_mock.go
  manager/service/persistent_cache.go
  manager/service/persistent_cache_task.go
  manager/service/service.go
  manager/types/persistent_cache_task.go
  pkg/redis/redis.go
  scheduler/resource/persistentcache/host_manager.go
  scheduler/resource/persistentcache/peer_manager.go
  scheduler/resource/persistentcache/task_manager.go
  scheduler/resource/persistentcache/task_manager_mock.go
Labels: enhancement

#3936 feat(client): removing hostname resolution fallback when the IP address check fails
  client/config/dynconfig_manager.go
  client/config/dynconfig_manager_test.go
Labels: enhancement

#3942 feat: add log for searcher plugin
  manager/searcher/searcher.go
  pkg/rpc/scheduler/server/server.go
Labels: enhancement

#3943 fix: replace builds with ids in config
  .goreleaser.yml
Labels: enhancement

#3945 feat: change PersistentCacheTask to value type and ensure empty slice response
  manager/service/mocks/service_mock.go
  manager/service/persistent_cache_task.go
  manager/service/service.go
  manager/types/persistent_cache_task.go
Labels: enhancement

#3952 test(e2e): optimize testing for preheating in cache
  cmd/dependency/plugin_cmd.go
  internal/dfplugin/dfplugin.go
  test/e2e/v2/concurrency_test.go
  test/e2e/v2/containerd_test.go
  test/e2e/v2/dfget_test.go
  test/e2e/v2/e2e_test.go
  test/e2e/v2/manager/preheat.go
  test/e2e/v2/manager/task.go
  test/e2e/v2/proxy_test.go
Labels: enhancement

#3954 fix(manager): fix peer ID logging in loadAllPeersByTaskID
  manager/service/persistent_cache_task.go
Labels: enhancement

#3959 chore(README.md): change OpenSSF badge
  README.md
Labels: enhancement

#3958 feat: adds the audit middleware to records the system audit events
  CHANGELOG.md
  api/manager/docs.go
  api/manager/swagger.json
  api/manager/swagger.yaml
  manager/database/database.go
  manager/handlers/audit.go
  manager/handlers/audit_test.go
  manager/middlewares/audit.go
  manager/middlewares/personal_access_token.go
  manager/models/audit.go
  manager/router/router.go
  manager/service/audit.go
  manager/service/mocks/service_mock.go
  manager/service/service.go
  manager/types/audit.go
Labels: enhancement

#3966 feat(manager): add default value for operated_at
  manager/models/audit.go
  manager/models/models.go
Labels: enhancement

#3970 feat: support query parameters for list audit API
  manager/handlers/audit_test.go
  manager/service/audit.go
  manager/types/audit.go
Labels: enhancement

#3986 feat: resolve statsview hanging issue by improving port handling and shutdown logic
  cmd/dependency/dependency.go
  cmd/manager/cmd/root.go
  cmd/scheduler/cmd/root.go
Labels: enhancement

#3987 feat: add the default gc config
  manager/database/database.go
  manager/models/config.go
Labels: enhancement

#3988 chore(.github/workflows/release.yml): update release workflow to correctly pass tag_name output to SLSA generator
  .github/workflows/release.yml
Labels: enhancement

#3990 fix: remove the gorm tag for CreatedAt and UpdatedAt
  manager/models/models.go
Labels: bug

#3991 refactor: migrate the job gc to mananger gc server
  manager/gc/job.go
  manager/gc/recorder.go
  manager/job/gc.go
  manager/job/job.go
  manager/manager.go
  manager/service/audit.go
Labels: enhancement

#3997 feat: support to preheat multiple files
  manager/job/preheat.go
  manager/types/job.go
Labels: enhancement

#3998 chore: add auto-assign workflows for pr assign
  .github/auto_assign.yml
  .github/workflows/auto-assign.yml
Labels: enhancement

#4000 chore(.github/workflows): add stale action
  .github/workflows/stale.yml
Labels: enhancement

#4004 chore(.github/workflows/release.yml): add custom SLSA provenance and SPDX file upload to release workflow
  .github/workflows/release.yml
Labels: enhancement

#4005 chore(.github/auto_assign.yml): add assignees for PR
  .github/auto_assign.yml
Labels: enhancement

#4007 fix: set the pat to context for audit
  manager/middlewares/personal_access_token.go
Labels: bug

#4009 comments(dferrors): add comments for IsGRPCDfError function to check …
  internal/dferrors/error.go
Labels: documentation

#4008 comments(dferrors): add comments for IsEndOfStream function to check …
  internal/dferrors/error.go
Labels: documentation

#4021 fix(.github/workflows): detected GitHub workflow tokens with excessive permissions in auto-assign.yml
  .github/workflows/auto-assign.yml
Labels: enhancement

#4023 feat: add unit tests for persistent cache task handlers
  manager/handlers/persistent_cache_task_test.go
Labels: enhancement

#4028 chore(.github/workflows): change rules of the stale actions
  .github/workflows/stale.yml
Labels: enhancement
